/*
 * This file is generated by jOOQ.
 */
package com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.daos;


import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.ProductCategoryMap;
import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.records.ProductCategoryMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryMapDao extends DAOImpl<ProductCategoryMapRecord, com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap, UInteger> {

    /**
     * Create a new ProductCategoryMapDao without any configuration
     */
    public ProductCategoryMapDao() {
        super(ProductCategoryMap.PRODUCT_CATEGORY_MAP, com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap.class);
    }

    /**
     * Create a new ProductCategoryMapDao with an attached configuration
     */
    public ProductCategoryMapDao(Configuration configuration) {
        super(ProductCategoryMap.PRODUCT_CATEGORY_MAP, com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap.class, configuration);
    }

    @Override
    public UInteger getId(com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap object) {
        return object.getProductCategoryMapId();
    }

    /**
     * Fetch records that have <code>product_category_map_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchRangeOfProductCategoryMapId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_category_map_id IN (values)</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchByProductCategoryMapId(UInteger... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_category_map_id =
     * value</code>
     */
    public com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap fetchOneByProductCategoryMapId(UInteger value) {
        return fetchOne(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_category_map_id =
     * value</code>
     */
    public Optional<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchOptionalByProductCategoryMapId(UInteger value) {
        return fetchOptional(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>product_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchRangeOfProductId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_id IN (values)</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchByProductId(UInteger... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>product_category_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchRangeOfProductCategoryId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_category_id IN (values)</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchByProductCategoryId(UInteger... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductCategoryMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.MODIFICATION_TIME, values);
    }
}
