/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.records;


import ecommerceservice.dataaccesslayer.tables.ProductBrand;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandRecord extends UpdatableRecordImpl<ProductBrandRecord> implements Record6<UInteger, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Catbirdnyc.product_brand.product_brand_id</code>.
     */
    public void setProductBrandId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.product_brand_id</code>.
     */
    public UInteger getProductBrandId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.brand_name</code>.
     */
    public void setBrandName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.brand_name</code>.
     */
    public String getBrandName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.brand_website</code>.
     */
    public void setBrandWebsite(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.brand_website</code>.
     */
    public String getBrandWebsite() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.brand_description</code>.
     */
    public void setBrandDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.brand_description</code>.
     */
    public String getBrandDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID;
    }

    @Override
    public Field<String> field2() {
        return ProductBrand.PRODUCT_BRAND.BRAND_NAME;
    }

    @Override
    public Field<String> field3() {
        return ProductBrand.PRODUCT_BRAND.BRAND_WEBSITE;
    }

    @Override
    public Field<String> field4() {
        return ProductBrand.PRODUCT_BRAND.BRAND_DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ProductBrand.PRODUCT_BRAND.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ProductBrand.PRODUCT_BRAND.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getProductBrandId();
    }

    @Override
    public String component2() {
        return getBrandName();
    }

    @Override
    public String component3() {
        return getBrandWebsite();
    }

    @Override
    public String component4() {
        return getBrandDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getProductBrandId();
    }

    @Override
    public String value2() {
        return getBrandName();
    }

    @Override
    public String value3() {
        return getBrandWebsite();
    }

    @Override
    public String value4() {
        return getBrandDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModificationTime();
    }

    @Override
    public ProductBrandRecord value1(UInteger value) {
        setProductBrandId(value);
        return this;
    }

    @Override
    public ProductBrandRecord value2(String value) {
        setBrandName(value);
        return this;
    }

    @Override
    public ProductBrandRecord value3(String value) {
        setBrandWebsite(value);
        return this;
    }

    @Override
    public ProductBrandRecord value4(String value) {
        setBrandDescription(value);
        return this;
    }

    @Override
    public ProductBrandRecord value5(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProductBrandRecord value6(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public ProductBrandRecord values(UInteger value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductBrandRecord
     */
    public ProductBrandRecord() {
        super(ProductBrand.PRODUCT_BRAND);
    }

    /**
     * Create a detached, initialised ProductBrandRecord
     */
    public ProductBrandRecord(UInteger productBrandId, String brandName, String brandWebsite, String brandDescription, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(ProductBrand.PRODUCT_BRAND);

        setProductBrandId(productBrandId);
        setBrandName(brandName);
        setBrandWebsite(brandWebsite);
        setBrandDescription(brandDescription);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised ProductBrandRecord
     */
    public ProductBrandRecord(ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand value) {
        super(ProductBrand.PRODUCT_BRAND);

        if (value != null) {
            setProductBrandId(value.getProductBrandId());
            setBrandName(value.getBrandName());
            setBrandWebsite(value.getBrandWebsite());
            setBrandDescription(value.getBrandDescription());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
