/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.records;


import ecommerceservice.dataaccesslayer.tables.ProductImage;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductImageRecord extends UpdatableRecordImpl<ProductImageRecord> implements Record5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Catbirdnyc.product_image.product_image_id</code>.
     */
    public void setProductImageId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.product_image_id</code>.
     */
    public UInteger getProductImageId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.product_id</code>.
     */
    public void setProductId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.product_id</code>.
     */
    public UInteger getProductId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.product_image_link</code>.
     */
    public void setProductImageLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.product_image_link</code>.
     */
    public String getProductImageLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return ProductImage.PRODUCT_IMAGE.PRODUCT_IMAGE_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return ProductImage.PRODUCT_IMAGE.PRODUCT_ID;
    }

    @Override
    public Field<String> field3() {
        return ProductImage.PRODUCT_IMAGE.PRODUCT_IMAGE_LINK;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProductImage.PRODUCT_IMAGE.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ProductImage.PRODUCT_IMAGE.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getProductImageId();
    }

    @Override
    public UInteger component2() {
        return getProductId();
    }

    @Override
    public String component3() {
        return getProductImageLink();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getProductImageId();
    }

    @Override
    public UInteger value2() {
        return getProductId();
    }

    @Override
    public String value3() {
        return getProductImageLink();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModificationTime();
    }

    @Override
    public ProductImageRecord value1(UInteger value) {
        setProductImageId(value);
        return this;
    }

    @Override
    public ProductImageRecord value2(UInteger value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductImageRecord value3(String value) {
        setProductImageLink(value);
        return this;
    }

    @Override
    public ProductImageRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProductImageRecord value5(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public ProductImageRecord values(UInteger value1, UInteger value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductImageRecord
     */
    public ProductImageRecord() {
        super(ProductImage.PRODUCT_IMAGE);
    }

    /**
     * Create a detached, initialised ProductImageRecord
     */
    public ProductImageRecord(UInteger productImageId, UInteger productId, String productImageLink, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(ProductImage.PRODUCT_IMAGE);

        setProductImageId(productImageId);
        setProductId(productId);
        setProductImageLink(productImageLink);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised ProductImageRecord
     */
    public ProductImageRecord(ecommerceservice.dataaccesslayer.tables.pojos.ProductImage value) {
        super(ProductImage.PRODUCT_IMAGE);

        if (value != null) {
            setProductImageId(value.getProductImageId());
            setProductId(value.getProductId());
            setProductImageLink(value.getProductImageLink());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
