/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.records;


import ecommerceservice.dataaccesslayer.tables.StoreLocation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreLocationRecord extends UpdatableRecordImpl<StoreLocationRecord> implements Record7<UInteger, UInteger, String, Double, Double, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Catbirdnyc.store_location.store_location_id</code>.
     */
    public void setStoreLocationId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.store_location_id</code>.
     */
    public UInteger getStoreLocationId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.store_location.store_id</code>.
     */
    public void setStoreId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.store_id</code>.
     */
    public UInteger getStoreId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.store_location.formatted_address</code>.
     */
    public void setFormattedAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.formatted_address</code>.
     */
    public String getFormattedAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.store_location.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>Catbirdnyc.store_location.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>Catbirdnyc.store_location.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>Catbirdnyc.store_location.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_location.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UInteger, UInteger, String, Double, Double, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UInteger, UInteger, String, Double, Double, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return StoreLocation.STORE_LOCATION.STORE_LOCATION_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return StoreLocation.STORE_LOCATION.STORE_ID;
    }

    @Override
    public Field<String> field3() {
        return StoreLocation.STORE_LOCATION.FORMATTED_ADDRESS;
    }

    @Override
    public Field<Double> field4() {
        return StoreLocation.STORE_LOCATION.LATITUDE;
    }

    @Override
    public Field<Double> field5() {
        return StoreLocation.STORE_LOCATION.LONGITUDE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return StoreLocation.STORE_LOCATION.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return StoreLocation.STORE_LOCATION.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getStoreLocationId();
    }

    @Override
    public UInteger component2() {
        return getStoreId();
    }

    @Override
    public String component3() {
        return getFormattedAddress();
    }

    @Override
    public Double component4() {
        return getLatitude();
    }

    @Override
    public Double component5() {
        return getLongitude();
    }

    @Override
    public LocalDateTime component6() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component7() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getStoreLocationId();
    }

    @Override
    public UInteger value2() {
        return getStoreId();
    }

    @Override
    public String value3() {
        return getFormattedAddress();
    }

    @Override
    public Double value4() {
        return getLatitude();
    }

    @Override
    public Double value5() {
        return getLongitude();
    }

    @Override
    public LocalDateTime value6() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value7() {
        return getModificationTime();
    }

    @Override
    public StoreLocationRecord value1(UInteger value) {
        setStoreLocationId(value);
        return this;
    }

    @Override
    public StoreLocationRecord value2(UInteger value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreLocationRecord value3(String value) {
        setFormattedAddress(value);
        return this;
    }

    @Override
    public StoreLocationRecord value4(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public StoreLocationRecord value5(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public StoreLocationRecord value6(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreLocationRecord value7(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreLocationRecord values(UInteger value1, UInteger value2, String value3, Double value4, Double value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreLocationRecord
     */
    public StoreLocationRecord() {
        super(StoreLocation.STORE_LOCATION);
    }

    /**
     * Create a detached, initialised StoreLocationRecord
     */
    public StoreLocationRecord(UInteger storeLocationId, UInteger storeId, String formattedAddress, Double latitude, Double longitude, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(StoreLocation.STORE_LOCATION);

        setStoreLocationId(storeLocationId);
        setStoreId(storeId);
        setFormattedAddress(formattedAddress);
        setLatitude(latitude);
        setLongitude(longitude);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreLocationRecord
     */
    public StoreLocationRecord(ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation value) {
        super(StoreLocation.STORE_LOCATION);

        if (value != null) {
            setStoreLocationId(value.getStoreLocationId());
            setStoreId(value.getStoreId());
            setFormattedAddress(value.getFormattedAddress());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
