/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.records;


import ecommerceservice.dataaccesslayer.tables.StoreImage;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreImageRecord extends UpdatableRecordImpl<StoreImageRecord> implements Record5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Catbirdnyc.store_image.store_image_id</code>.
     */
    public void setStoreImageId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.store_image_id</code>.
     */
    public UInteger getStoreImageId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.store_id</code>.
     */
    public void setStoreId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.store_id</code>.
     */
    public UInteger getStoreId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.store_image_link</code>.
     */
    public void setStoreImageLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.store_image_link</code>.
     */
    public String getStoreImageLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return StoreImage.STORE_IMAGE.STORE_IMAGE_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return StoreImage.STORE_IMAGE.STORE_ID;
    }

    @Override
    public Field<String> field3() {
        return StoreImage.STORE_IMAGE.STORE_IMAGE_LINK;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return StoreImage.STORE_IMAGE.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return StoreImage.STORE_IMAGE.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getStoreImageId();
    }

    @Override
    public UInteger component2() {
        return getStoreId();
    }

    @Override
    public String component3() {
        return getStoreImageLink();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getStoreImageId();
    }

    @Override
    public UInteger value2() {
        return getStoreId();
    }

    @Override
    public String value3() {
        return getStoreImageLink();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModificationTime();
    }

    @Override
    public StoreImageRecord value1(UInteger value) {
        setStoreImageId(value);
        return this;
    }

    @Override
    public StoreImageRecord value2(UInteger value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreImageRecord value3(String value) {
        setStoreImageLink(value);
        return this;
    }

    @Override
    public StoreImageRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreImageRecord value5(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreImageRecord values(UInteger value1, UInteger value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreImageRecord
     */
    public StoreImageRecord() {
        super(StoreImage.STORE_IMAGE);
    }

    /**
     * Create a detached, initialised StoreImageRecord
     */
    public StoreImageRecord(UInteger storeImageId, UInteger storeId, String storeImageLink, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(StoreImage.STORE_IMAGE);

        setStoreImageId(storeImageId);
        setStoreId(storeId);
        setStoreImageLink(storeImageLink);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreImageRecord
     */
    public StoreImageRecord(ecommerceservice.dataaccesslayer.tables.pojos.StoreImage value) {
        super(StoreImage.STORE_IMAGE);

        if (value != null) {
            setStoreImageId(value.getStoreImageId());
            setStoreId(value.getStoreId());
            setStoreImageLink(value.getStoreImageLink());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
