/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.records;


import ecommerceservice.dataaccesslayer.tables.StoreCategory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryRecord extends UpdatableRecordImpl<StoreCategoryRecord> implements Record4<UInteger, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Catbirdnyc.store_category.store_category_id</code>.
     */
    public void setStoreCategoryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category.store_category_id</code>.
     */
    public UInteger getStoreCategoryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category.category_type</code>.
     */
    public void setCategoryType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category.category_type</code>.
     */
    public String getCategoryType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UInteger, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID;
    }

    @Override
    public Field<String> field2() {
        return StoreCategory.STORE_CATEGORY.CATEGORY_TYPE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return StoreCategory.STORE_CATEGORY.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return StoreCategory.STORE_CATEGORY.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getStoreCategoryId();
    }

    @Override
    public String component2() {
        return getCategoryType();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component4() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getStoreCategoryId();
    }

    @Override
    public String value2() {
        return getCategoryType();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value4() {
        return getModificationTime();
    }

    @Override
    public StoreCategoryRecord value1(UInteger value) {
        setStoreCategoryId(value);
        return this;
    }

    @Override
    public StoreCategoryRecord value2(String value) {
        setCategoryType(value);
        return this;
    }

    @Override
    public StoreCategoryRecord value3(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreCategoryRecord value4(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreCategoryRecord values(UInteger value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreCategoryRecord
     */
    public StoreCategoryRecord() {
        super(StoreCategory.STORE_CATEGORY);
    }

    /**
     * Create a detached, initialised StoreCategoryRecord
     */
    public StoreCategoryRecord(UInteger storeCategoryId, String categoryType, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(StoreCategory.STORE_CATEGORY);

        setStoreCategoryId(storeCategoryId);
        setCategoryType(categoryType);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreCategoryRecord
     */
    public StoreCategoryRecord(ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory value) {
        super(StoreCategory.STORE_CATEGORY);

        if (value != null) {
            setStoreCategoryId(value.getStoreCategoryId());
            setCategoryType(value.getCategoryType());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
