/*
 * This file is generated by jOOQ.
 */
package eCommerceServiceDataAccessLayer.tables.records;


import eCommerceServiceDataAccessLayer.tables.ProductTagMap;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagMapRecord extends UpdatableRecordImpl<ProductTagMapRecord> implements Record5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.product_tag_map_id</code>.
     */
    public void setProductTagMapId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.product_tag_map_id</code>.
     */
    public UInteger getProductTagMapId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.product_id</code>.
     */
    public void setProductId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.product_id</code>.
     */
    public UInteger getProductId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.product_tag_id</code>.
     */
    public void setProductTagId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.product_tag_id</code>.
     */
    public UInteger getProductTagId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID;
    }

    @Override
    public Field<UInteger> field3() {
        return ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProductTagMap.PRODUCT_TAG_MAP.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ProductTagMap.PRODUCT_TAG_MAP.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getProductTagMapId();
    }

    @Override
    public UInteger component2() {
        return getProductId();
    }

    @Override
    public UInteger component3() {
        return getProductTagId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getProductTagMapId();
    }

    @Override
    public UInteger value2() {
        return getProductId();
    }

    @Override
    public UInteger value3() {
        return getProductTagId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModificationTime();
    }

    @Override
    public ProductTagMapRecord value1(UInteger value) {
        setProductTagMapId(value);
        return this;
    }

    @Override
    public ProductTagMapRecord value2(UInteger value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductTagMapRecord value3(UInteger value) {
        setProductTagId(value);
        return this;
    }

    @Override
    public ProductTagMapRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProductTagMapRecord value5(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public ProductTagMapRecord values(UInteger value1, UInteger value2, UInteger value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductTagMapRecord
     */
    public ProductTagMapRecord() {
        super(ProductTagMap.PRODUCT_TAG_MAP);
    }

    /**
     * Create a detached, initialised ProductTagMapRecord
     */
    public ProductTagMapRecord(UInteger productTagMapId, UInteger productId, UInteger productTagId, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(ProductTagMap.PRODUCT_TAG_MAP);

        setProductTagMapId(productTagMapId);
        setProductId(productId);
        setProductTagId(productTagId);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised ProductTagMapRecord
     */
    public ProductTagMapRecord(eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap value) {
        super(ProductTagMap.PRODUCT_TAG_MAP);

        if (value != null) {
            setProductTagMapId(value.getProductTagMapId());
            setProductId(value.getProductId());
            setProductTagId(value.getProductTagId());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
