/*
 * This file is generated by jOOQ.
 */
package eCommerceServiceDataAccessLayer.tables.daos;


import eCommerceServiceDataAccessLayer.tables.ProductTagMap;
import eCommerceServiceDataAccessLayer.tables.records.ProductTagMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagMapDao extends DAOImpl<ProductTagMapRecord, eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap, UInteger> {

    /**
     * Create a new ProductTagMapDao without any configuration
     */
    public ProductTagMapDao() {
        super(ProductTagMap.PRODUCT_TAG_MAP, eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap.class);
    }

    /**
     * Create a new ProductTagMapDao with an attached configuration
     */
    public ProductTagMapDao(Configuration configuration) {
        super(ProductTagMap.PRODUCT_TAG_MAP, eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap.class, configuration);
    }

    @Override
    public UInteger getId(eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap object) {
        return object.getProductTagMapId();
    }

    /**
     * Fetch records that have <code>product_tag_map_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchRangeOfProductTagMapId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_tag_map_id IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchByProductTagMapId(UInteger... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_tag_map_id = value</code>
     */
    public eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap fetchOneByProductTagMapId(UInteger value) {
        return fetchOne(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_tag_map_id = value</code>
     */
    public Optional<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchOptionalByProductTagMapId(UInteger value) {
        return fetchOptional(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>product_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchRangeOfProductId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_id IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchByProductId(UInteger... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>product_tag_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchRangeOfProductTagId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_tag_id IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchByProductTagId(UInteger... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductTagMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.MODIFICATION_TIME, values);
    }
}
