/*
 * This file is generated by jOOQ.
 */
package eCommerceServiceDataAccessLayer.tables.daos;


import eCommerceServiceDataAccessLayer.tables.ProductBrandMap;
import eCommerceServiceDataAccessLayer.tables.records.ProductBrandMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandMapDao extends DAOImpl<ProductBrandMapRecord, eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap, UInteger> {

    /**
     * Create a new ProductBrandMapDao without any configuration
     */
    public ProductBrandMapDao() {
        super(ProductBrandMap.PRODUCT_BRAND_MAP, eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap.class);
    }

    /**
     * Create a new ProductBrandMapDao with an attached configuration
     */
    public ProductBrandMapDao(Configuration configuration) {
        super(ProductBrandMap.PRODUCT_BRAND_MAP, eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap.class, configuration);
    }

    @Override
    public UInteger getId(eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap object) {
        return object.getProductBrandMapId();
    }

    /**
     * Fetch records that have <code>product_brand_map_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchRangeOfProductBrandMapId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_brand_map_id IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchByProductBrandMapId(UInteger... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_brand_map_id = value</code>
     */
    public eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap fetchOneByProductBrandMapId(UInteger value) {
        return fetchOne(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_brand_map_id = value</code>
     */
    public Optional<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchOptionalByProductBrandMapId(UInteger value) {
        return fetchOptional(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>product_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchRangeOfProductId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_id IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchByProductId(UInteger... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>product_brand_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchRangeOfProductBrandId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_brand_id IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchByProductBrandId(UInteger... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<eCommerceServiceDataAccessLayer.tables.pojos.ProductBrandMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.MODIFICATION_TIME, values);
    }
}
