/*
 * This file is generated by jOOQ.
 */
package eCommerceServiceDataAccessLayer.tables;


import eCommerceServiceDataAccessLayer.Catbirdnyc;
import eCommerceServiceDataAccessLayer.Keys;
import eCommerceServiceDataAccessLayer.tables.records.StoreOwnerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreOwner extends TableImpl<StoreOwnerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.store_owner</code>
     */
    public static final StoreOwner STORE_OWNER = new StoreOwner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreOwnerRecord> getRecordType() {
        return StoreOwnerRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.store_owner.store_owner_id</code>.
     */
    public final TableField<StoreOwnerRecord, UInteger> STORE_OWNER_ID = createField(DSL.name("store_owner_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.store_id</code>.
     */
    public final TableField<StoreOwnerRecord, UInteger> STORE_ID = createField(DSL.name("store_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.cognito_user_id</code>.
     */
    public final TableField<StoreOwnerRecord, String> COGNITO_USER_ID = createField(DSL.name("cognito_user_id"), SQLDataType.VARCHAR(96), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.cognito_user_pool_id</code>.
     */
    public final TableField<StoreOwnerRecord, String> COGNITO_USER_POOL_ID = createField(DSL.name("cognito_user_pool_id"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.email</code>.
     */
    public final TableField<StoreOwnerRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.phone_number</code>.
     */
    public final TableField<StoreOwnerRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.username</code>.
     */
    public final TableField<StoreOwnerRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.profile_picture_link</code>.
     */
    public final TableField<StoreOwnerRecord, String> PROFILE_PICTURE_LINK = createField(DSL.name("profile_picture_link"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.is_banned</code>.
     */
    public final TableField<StoreOwnerRecord, Byte> IS_BANNED = createField(DSL.name("is_banned"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.creation_time</code>.
     */
    public final TableField<StoreOwnerRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.store_owner.modification_time</code>.
     */
    public final TableField<StoreOwnerRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private StoreOwner(Name alias, Table<StoreOwnerRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoreOwner(Name alias, Table<StoreOwnerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.store_owner</code> table reference
     */
    public StoreOwner(String alias) {
        this(DSL.name(alias), STORE_OWNER);
    }

    /**
     * Create an aliased <code>Catbirdnyc.store_owner</code> table reference
     */
    public StoreOwner(Name alias) {
        this(alias, STORE_OWNER);
    }

    /**
     * Create a <code>Catbirdnyc.store_owner</code> table reference
     */
    public StoreOwner() {
        this(DSL.name("store_owner"), null);
    }

    public <O extends Record> StoreOwner(Table<O> child, ForeignKey<O, StoreOwnerRecord> key) {
        super(child, key, STORE_OWNER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public Identity<StoreOwnerRecord, UInteger> getIdentity() {
        return (Identity<StoreOwnerRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoreOwnerRecord> getPrimaryKey() {
        return Keys.KEY_STORE_OWNER_PRIMARY;
    }

    @Override
    public List<UniqueKey<StoreOwnerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_STORE_OWNER_COGNITO_USER_ID, Keys.KEY_STORE_OWNER_EMAIL, Keys.KEY_STORE_OWNER_PHONE_NUMBER, Keys.KEY_STORE_OWNER_USERNAME);
    }

    @Override
    public List<ForeignKey<StoreOwnerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_STORE_OWNER_RT_STORE_RC_STORE_ID);
    }

    private transient Store _store;

    /**
     * Get the implicit join path to the <code>Catbirdnyc.store</code> table.
     */
    public Store store() {
        if (_store == null)
            _store = new Store(this, Keys.FK_STORE_OWNER_RT_STORE_RC_STORE_ID);

        return _store;
    }

    @Override
    public StoreOwner as(String alias) {
        return new StoreOwner(DSL.name(alias), this);
    }

    @Override
    public StoreOwner as(Name alias) {
        return new StoreOwner(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreOwner rename(String name) {
        return new StoreOwner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreOwner rename(Name name) {
        return new StoreOwner(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<UInteger, UInteger, String, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
