/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.Customer;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.CustomerRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerDao extends DAOImpl<CustomerRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer, Long> {

    /**
     * Create a new CustomerDao without any configuration
     */
    public CustomerDao() {
        super(Customer.CUSTOMER, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer.class);
    }

    /**
     * Create a new CustomerDao with an attached configuration
     */
    public CustomerDao(Configuration configuration) {
        super(Customer.CUSTOMER, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer object) {
        return object.getCustomerId();
    }

    /**
     * Fetch records that have <code>CUSTOMER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfCustomerId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Customer.CUSTOMER.CUSTOMER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CUSTOMER_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByCustomerId(Long... values) {
        return fetch(Customer.CUSTOMER.CUSTOMER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>CUSTOMER_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer fetchOneByCustomerId(Long value) {
        return fetchOne(Customer.CUSTOMER.CUSTOMER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>CUSTOMER_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchOptionalByCustomerId(Long value) {
        return fetchOptional(Customer.CUSTOMER.CUSTOMER_ID, value);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfCognitoUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customer.CUSTOMER.COGNITO_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByCognitoUserId(String... values) {
        return fetch(Customer.CUSTOMER.COGNITO_USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>COGNITO_USER_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer fetchOneByCognitoUserId(String value) {
        return fetchOne(Customer.CUSTOMER.COGNITO_USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>COGNITO_USER_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchOptionalByCognitoUserId(String value) {
        return fetchOptional(Customer.CUSTOMER.COGNITO_USER_ID, value);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_POOL_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfCognitoUserPoolId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customer.CUSTOMER.COGNITO_USER_POOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_POOL_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByCognitoUserPoolId(String... values) {
        return fetch(Customer.CUSTOMER.COGNITO_USER_POOL_ID, values);
    }

    /**
     * Fetch records that have <code>EMAIL BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customer.CUSTOMER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>EMAIL IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByEmail(String... values) {
        return fetch(Customer.CUSTOMER.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>EMAIL = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer fetchOneByEmail(String value) {
        return fetchOne(Customer.CUSTOMER.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>EMAIL = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchOptionalByEmail(String value) {
        return fetchOptional(Customer.CUSTOMER.EMAIL, value);
    }

    /**
     * Fetch records that have <code>PHONE_NUMBER BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customer.CUSTOMER.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PHONE_NUMBER IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByPhoneNumber(String... values) {
        return fetch(Customer.CUSTOMER.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>USERNAME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customer.CUSTOMER.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByUsername(String... values) {
        return fetch(Customer.CUSTOMER.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>USERNAME = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer fetchOneByUsername(String value) {
        return fetchOne(Customer.CUSTOMER.USERNAME, value);
    }

    /**
     * Fetch a unique record that has <code>USERNAME = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchOptionalByUsername(String value) {
        return fetchOptional(Customer.CUSTOMER.USERNAME, value);
    }

    /**
     * Fetch records that have <code>PROFILE_PICTURE_LINK BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfProfilePictureLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customer.CUSTOMER.PROFILE_PICTURE_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PROFILE_PICTURE_LINK IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByProfilePictureLink(String... values) {
        return fetch(Customer.CUSTOMER.PROFILE_PICTURE_LINK, values);
    }

    /**
     * Fetch records that have <code>IS_BANNED BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfIsBanned(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Customer.CUSTOMER.IS_BANNED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>IS_BANNED IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByIsBanned(Boolean... values) {
        return fetch(Customer.CUSTOMER.IS_BANNED, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Customer.CUSTOMER.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByCreationTime(LocalDateTime... values) {
        return fetch(Customer.CUSTOMER.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Customer.CUSTOMER.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Customer> fetchByModificationTime(LocalDateTime... values) {
        return fetch(Customer.CUSTOMER.MODIFICATION_TIME, values);
    }
}
