/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductCategory;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductCategoryRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryDao extends DAOImpl<ProductCategoryRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory, Long> {

    /**
     * Create a new ProductCategoryDao without any configuration
     */
    public ProductCategoryDao() {
        super(ProductCategory.PRODUCT_CATEGORY, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory.class);
    }

    /**
     * Create a new ProductCategoryDao with an attached configuration
     */
    public ProductCategoryDao(Configuration configuration) {
        super(ProductCategory.PRODUCT_CATEGORY, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory object) {
        return object.getProductCategoryId();
    }

    /**
     * Fetch records that have <code>PRODUCT_CATEGORY_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfProductCategoryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_CATEGORY_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByProductCategoryId(Long... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_CATEGORY_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory fetchOneByProductCategoryId(Long value) {
        return fetchOne(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, value);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_CATEGORY_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchOptionalByProductCategoryId(Long value) {
        return fetchOptional(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>CATEGORY_TYPE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfCategoryType(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CATEGORY_TYPE IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByCategoryType(String... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, values);
    }

    /**
     * Fetch a unique record that has <code>CATEGORY_TYPE = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory fetchOneByCategoryType(String value) {
        return fetchOne(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch a unique record that has <code>CATEGORY_TYPE = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchOptionalByCategoryType(String value) {
        return fetchOptional(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.MODIFICATION_TIME, values);
    }
}
