/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductTagMap;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductTagMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagMapDao extends DAOImpl<ProductTagMapRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap, Long> {

    /**
     * Create a new ProductTagMapDao without any configuration
     */
    public ProductTagMapDao() {
        super(ProductTagMap.PRODUCT_TAG_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap.class);
    }

    /**
     * Create a new ProductTagMapDao with an attached configuration
     */
    public ProductTagMapDao(Configuration configuration) {
        super(ProductTagMap.PRODUCT_TAG_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap object) {
        return object.getProductTagMapId();
    }

    /**
     * Fetch records that have <code>PRODUCT_TAG_MAP_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchRangeOfProductTagMapId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_TAG_MAP_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchByProductTagMapId(Long... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_TAG_MAP_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap fetchOneByProductTagMapId(Long value) {
        return fetchOne(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_TAG_MAP_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchOptionalByProductTagMapId(Long value) {
        return fetchOptional(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchRangeOfProductId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchByProductId(Long... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>PRODUCT_TAG_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchRangeOfProductTagId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_TAG_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchByProductTagId(Long... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductTagMap.PRODUCT_TAG_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductTagMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductTagMap.PRODUCT_TAG_MAP.MODIFICATION_TIME, values);
    }
}
