/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductCategoryMap;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductCategoryMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryMapDao extends DAOImpl<ProductCategoryMapRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap, Long> {

    /**
     * Create a new ProductCategoryMapDao without any configuration
     */
    public ProductCategoryMapDao() {
        super(ProductCategoryMap.PRODUCT_CATEGORY_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap.class);
    }

    /**
     * Create a new ProductCategoryMapDao with an attached configuration
     */
    public ProductCategoryMapDao(Configuration configuration) {
        super(ProductCategoryMap.PRODUCT_CATEGORY_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap object) {
        return object.getProductCategoryMapId();
    }

    /**
     * Fetch records that have <code>PRODUCT_CATEGORY_MAP_ID BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchRangeOfProductCategoryMapId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_CATEGORY_MAP_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchByProductCategoryMapId(Long... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_CATEGORY_MAP_ID =
     * value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap fetchOneByProductCategoryMapId(Long value) {
        return fetchOne(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_CATEGORY_MAP_ID =
     * value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchOptionalByProductCategoryMapId(Long value) {
        return fetchOptional(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchRangeOfProductId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchByProductId(Long... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>PRODUCT_CATEGORY_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchRangeOfProductCategoryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_CATEGORY_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchByProductCategoryId(Long... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategoryMap.PRODUCT_CATEGORY_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategoryMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductCategoryMap.PRODUCT_CATEGORY_MAP.MODIFICATION_TIME, values);
    }
}
