/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductBrandMap;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductBrandMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandMapDao extends DAOImpl<ProductBrandMapRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap, Long> {

    /**
     * Create a new ProductBrandMapDao without any configuration
     */
    public ProductBrandMapDao() {
        super(ProductBrandMap.PRODUCT_BRAND_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap.class);
    }

    /**
     * Create a new ProductBrandMapDao with an attached configuration
     */
    public ProductBrandMapDao(Configuration configuration) {
        super(ProductBrandMap.PRODUCT_BRAND_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap object) {
        return object.getProductBrandMapId();
    }

    /**
     * Fetch records that have <code>PRODUCT_BRAND_MAP_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchRangeOfProductBrandMapId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_BRAND_MAP_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchByProductBrandMapId(Long... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_BRAND_MAP_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap fetchOneByProductBrandMapId(Long value) {
        return fetchOne(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_BRAND_MAP_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchOptionalByProductBrandMapId(Long value) {
        return fetchOptional(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchRangeOfProductId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchByProductId(Long... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>PRODUCT_BRAND_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchRangeOfProductBrandId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_BRAND_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchByProductBrandId(Long... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductBrandMap.PRODUCT_BRAND_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductBrandMap.PRODUCT_BRAND_MAP.MODIFICATION_TIME, values);
    }
}
