/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductCategory;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductCategoryRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryDao extends DAOImpl<ProductCategoryRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory, UInteger> {

    /**
     * Create a new ProductCategoryDao without any configuration
     */
    public ProductCategoryDao() {
        super(ProductCategory.PRODUCT_CATEGORY, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory.class);
    }

    /**
     * Create a new ProductCategoryDao with an attached configuration
     */
    public ProductCategoryDao(Configuration configuration) {
        super(ProductCategory.PRODUCT_CATEGORY, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory.class, configuration);
    }

    @Override
    public UInteger getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory object) {
        return object.getProductCategoryId();
    }

    /**
     * Fetch records that have <code>product_category_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfProductCategoryId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_category_id IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByProductCategoryId(UInteger... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_category_id = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory fetchOneByProductCategoryId(UInteger value) {
        return fetchOne(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_category_id = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchOptionalByProductCategoryId(UInteger value) {
        return fetchOptional(ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>category_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfCategoryType(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category_type IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByCategoryType(String... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, values);
    }

    /**
     * Fetch a unique record that has <code>category_type = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory fetchOneByCategoryType(String value) {
        return fetchOne(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch a unique record that has <code>category_type = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchOptionalByCategoryType(String value) {
        return fetchOptional(ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductCategory.PRODUCT_CATEGORY.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.MODIFICATION_TIME, values);
    }
}
