/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductBrand;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductBrandRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandDao extends DAOImpl<ProductBrandRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand, Long> {

    /**
     * Create a new ProductBrandDao without any configuration
     */
    public ProductBrandDao() {
        super(ProductBrand.PRODUCT_BRAND, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand.class);
    }

    /**
     * Create a new ProductBrandDao with an attached configuration
     */
    public ProductBrandDao(Configuration configuration) {
        super(ProductBrand.PRODUCT_BRAND, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand object) {
        return object.getProductBrandId();
    }

    /**
     * Fetch records that have <code>PRODUCT_BRAND_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchRangeOfProductBrandId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PRODUCT_BRAND_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchByProductBrandId(Long... values) {
        return fetch(ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_BRAND_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand fetchOneByProductBrandId(Long value) {
        return fetchOne(ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID, value);
    }

    /**
     * Fetch a unique record that has <code>PRODUCT_BRAND_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchOptionalByProductBrandId(Long value) {
        return fetchOptional(ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID, value);
    }

    /**
     * Fetch records that have <code>BRAND_NAME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchRangeOfBrandName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductBrand.PRODUCT_BRAND.BRAND_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>BRAND_NAME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchByBrandName(String... values) {
        return fetch(ProductBrand.PRODUCT_BRAND.BRAND_NAME, values);
    }

    /**
     * Fetch records that have <code>BRAND_WEBSITE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchRangeOfBrandWebsite(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductBrand.PRODUCT_BRAND.BRAND_WEBSITE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>BRAND_WEBSITE IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchByBrandWebsite(String... values) {
        return fetch(ProductBrand.PRODUCT_BRAND.BRAND_WEBSITE, values);
    }

    /**
     * Fetch records that have <code>BRAND_DESCRIPTION BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchRangeOfBrandDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductBrand.PRODUCT_BRAND.BRAND_DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>BRAND_DESCRIPTION IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchByBrandDescription(String... values) {
        return fetch(ProductBrand.PRODUCT_BRAND.BRAND_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductBrand.PRODUCT_BRAND.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductBrand.PRODUCT_BRAND.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductBrand.PRODUCT_BRAND.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrand> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductBrand.PRODUCT_BRAND.MODIFICATION_TIME, values);
    }
}
