/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreLocation;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreLocationRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreLocationDao extends DAOImpl<StoreLocationRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation, Long> {

    /**
     * Create a new StoreLocationDao without any configuration
     */
    public StoreLocationDao() {
        super(StoreLocation.STORE_LOCATION, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation.class);
    }

    /**
     * Create a new StoreLocationDao with an attached configuration
     */
    public StoreLocationDao(Configuration configuration) {
        super(StoreLocation.STORE_LOCATION, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation object) {
        return object.getStoreLocationId();
    }

    /**
     * Fetch records that have <code>STORE_LOCATION_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfStoreLocationId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_LOCATION_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByStoreLocationId(Long... values) {
        return fetch(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>STORE_LOCATION_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation fetchOneByStoreLocationId(Long value) {
        return fetchOne(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, value);
    }

    /**
     * Fetch a unique record that has <code>STORE_LOCATION_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchOptionalByStoreLocationId(Long value) {
        return fetchOptional(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, value);
    }

    /**
     * Fetch records that have <code>STORE_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfStoreId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByStoreId(Long... values) {
        return fetch(StoreLocation.STORE_LOCATION.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>FORMATTED_ADDRESS BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfFormattedAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.FORMATTED_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>FORMATTED_ADDRESS IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByFormattedAddress(String... values) {
        return fetch(StoreLocation.STORE_LOCATION.FORMATTED_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>LATITUDE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfLatitude(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.LATITUDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>LATITUDE IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByLatitude(BigDecimal... values) {
        return fetch(StoreLocation.STORE_LOCATION.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>LONGITUDE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfLongitude(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.LONGITUDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>LONGITUDE IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByLongitude(BigDecimal... values) {
        return fetch(StoreLocation.STORE_LOCATION.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreLocation.STORE_LOCATION.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreLocation.STORE_LOCATION.MODIFICATION_TIME, values);
    }
}
