/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreLocation;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreLocationRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreLocationDao extends DAOImpl<StoreLocationRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation, UInteger> {

    /**
     * Create a new StoreLocationDao without any configuration
     */
    public StoreLocationDao() {
        super(StoreLocation.STORE_LOCATION, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation.class);
    }

    /**
     * Create a new StoreLocationDao with an attached configuration
     */
    public StoreLocationDao(Configuration configuration) {
        super(StoreLocation.STORE_LOCATION, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation.class, configuration);
    }

    @Override
    public UInteger getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation object) {
        return object.getStoreLocationId();
    }

    /**
     * Fetch records that have <code>store_location_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfStoreLocationId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_location_id IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByStoreLocationId(UInteger... values) {
        return fetch(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>store_location_id = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation fetchOneByStoreLocationId(UInteger value) {
        return fetchOne(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, value);
    }

    /**
     * Fetch a unique record that has <code>store_location_id = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchOptionalByStoreLocationId(UInteger value) {
        return fetchOptional(StoreLocation.STORE_LOCATION.STORE_LOCATION_ID, value);
    }

    /**
     * Fetch records that have <code>store_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfStoreId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByStoreId(UInteger... values) {
        return fetch(StoreLocation.STORE_LOCATION.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>formatted_address BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfFormattedAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.FORMATTED_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>formatted_address IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByFormattedAddress(String... values) {
        return fetch(StoreLocation.STORE_LOCATION.FORMATTED_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>latitude BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfLatitude(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.LATITUDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByLatitude(Double... values) {
        return fetch(StoreLocation.STORE_LOCATION.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>longitude BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfLongitude(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.LONGITUDE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByLongitude(Double... values) {
        return fetch(StoreLocation.STORE_LOCATION.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreLocation.STORE_LOCATION.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreLocation.STORE_LOCATION.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreLocation> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreLocation.STORE_LOCATION.MODIFICATION_TIME, values);
    }
}
