/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreImage;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreImageRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreImageDao extends DAOImpl<StoreImageRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage, Long> {

    /**
     * Create a new StoreImageDao without any configuration
     */
    public StoreImageDao() {
        super(StoreImage.STORE_IMAGE, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage.class);
    }

    /**
     * Create a new StoreImageDao with an attached configuration
     */
    public StoreImageDao(Configuration configuration) {
        super(StoreImage.STORE_IMAGE, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage object) {
        return object.getStoreImageId();
    }

    /**
     * Fetch records that have <code>STORE_IMAGE_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchRangeOfStoreImageId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreImage.STORE_IMAGE.STORE_IMAGE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_IMAGE_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchByStoreImageId(Long... values) {
        return fetch(StoreImage.STORE_IMAGE.STORE_IMAGE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>STORE_IMAGE_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage fetchOneByStoreImageId(Long value) {
        return fetchOne(StoreImage.STORE_IMAGE.STORE_IMAGE_ID, value);
    }

    /**
     * Fetch a unique record that has <code>STORE_IMAGE_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchOptionalByStoreImageId(Long value) {
        return fetchOptional(StoreImage.STORE_IMAGE.STORE_IMAGE_ID, value);
    }

    /**
     * Fetch records that have <code>STORE_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchRangeOfStoreId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreImage.STORE_IMAGE.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchByStoreId(Long... values) {
        return fetch(StoreImage.STORE_IMAGE.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>STORE_IMAGE_LINK BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchRangeOfStoreImageLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreImage.STORE_IMAGE.STORE_IMAGE_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_IMAGE_LINK IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchByStoreImageLink(String... values) {
        return fetch(StoreImage.STORE_IMAGE.STORE_IMAGE_LINK, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreImage.STORE_IMAGE.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreImage.STORE_IMAGE.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreImage.STORE_IMAGE.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreImage> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreImage.STORE_IMAGE.MODIFICATION_TIME, values);
    }
}
