/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreOwner;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreOwnerRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreOwnerDao extends DAOImpl<StoreOwnerRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner, Long> {

    /**
     * Create a new StoreOwnerDao without any configuration
     */
    public StoreOwnerDao() {
        super(StoreOwner.STORE_OWNER, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner.class);
    }

    /**
     * Create a new StoreOwnerDao with an attached configuration
     */
    public StoreOwnerDao(Configuration configuration) {
        super(StoreOwner.STORE_OWNER, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner object) {
        return object.getStoreOwnerId();
    }

    /**
     * Fetch records that have <code>STORE_OWNER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfStoreOwnerId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.STORE_OWNER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_OWNER_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByStoreOwnerId(Long... values) {
        return fetch(StoreOwner.STORE_OWNER.STORE_OWNER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>STORE_OWNER_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner fetchOneByStoreOwnerId(Long value) {
        return fetchOne(StoreOwner.STORE_OWNER.STORE_OWNER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>STORE_OWNER_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchOptionalByStoreOwnerId(Long value) {
        return fetchOptional(StoreOwner.STORE_OWNER.STORE_OWNER_ID, value);
    }

    /**
     * Fetch records that have <code>STORE_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfStoreId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByStoreId(Long... values) {
        return fetch(StoreOwner.STORE_OWNER.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfCognitoUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.COGNITO_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByCognitoUserId(String... values) {
        return fetch(StoreOwner.STORE_OWNER.COGNITO_USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>COGNITO_USER_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner fetchOneByCognitoUserId(String value) {
        return fetchOne(StoreOwner.STORE_OWNER.COGNITO_USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>COGNITO_USER_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchOptionalByCognitoUserId(String value) {
        return fetchOptional(StoreOwner.STORE_OWNER.COGNITO_USER_ID, value);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_POOL_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfCognitoUserPoolId(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.COGNITO_USER_POOL_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>COGNITO_USER_POOL_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByCognitoUserPoolId(String... values) {
        return fetch(StoreOwner.STORE_OWNER.COGNITO_USER_POOL_ID, values);
    }

    /**
     * Fetch records that have <code>EMAIL BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>EMAIL IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByEmail(String... values) {
        return fetch(StoreOwner.STORE_OWNER.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>EMAIL = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner fetchOneByEmail(String value) {
        return fetchOne(StoreOwner.STORE_OWNER.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>EMAIL = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchOptionalByEmail(String value) {
        return fetchOptional(StoreOwner.STORE_OWNER.EMAIL, value);
    }

    /**
     * Fetch records that have <code>PHONE_NUMBER BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PHONE_NUMBER IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByPhoneNumber(String... values) {
        return fetch(StoreOwner.STORE_OWNER.PHONE_NUMBER, values);
    }

    /**
     * Fetch a unique record that has <code>PHONE_NUMBER = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner fetchOneByPhoneNumber(String value) {
        return fetchOne(StoreOwner.STORE_OWNER.PHONE_NUMBER, value);
    }

    /**
     * Fetch a unique record that has <code>PHONE_NUMBER = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchOptionalByPhoneNumber(String value) {
        return fetchOptional(StoreOwner.STORE_OWNER.PHONE_NUMBER, value);
    }

    /**
     * Fetch records that have <code>USERNAME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByUsername(String... values) {
        return fetch(StoreOwner.STORE_OWNER.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>USERNAME = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner fetchOneByUsername(String value) {
        return fetchOne(StoreOwner.STORE_OWNER.USERNAME, value);
    }

    /**
     * Fetch a unique record that has <code>USERNAME = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchOptionalByUsername(String value) {
        return fetchOptional(StoreOwner.STORE_OWNER.USERNAME, value);
    }

    /**
     * Fetch records that have <code>PROFILE_PICTURE_LINK BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfProfilePictureLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.PROFILE_PICTURE_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PROFILE_PICTURE_LINK IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByProfilePictureLink(String... values) {
        return fetch(StoreOwner.STORE_OWNER.PROFILE_PICTURE_LINK, values);
    }

    /**
     * Fetch records that have <code>IS_BANNED BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfIsBanned(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.IS_BANNED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>IS_BANNED IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByIsBanned(Boolean... values) {
        return fetch(StoreOwner.STORE_OWNER.IS_BANNED, values);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreOwner.STORE_OWNER.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreOwner.STORE_OWNER.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreOwner.STORE_OWNER.MODIFICATION_TIME, values);
    }
}
