/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreCategory;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreCategoryRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryDao extends DAOImpl<StoreCategoryRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory, Long> {

    /**
     * Create a new StoreCategoryDao without any configuration
     */
    public StoreCategoryDao() {
        super(StoreCategory.STORE_CATEGORY, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory.class);
    }

    /**
     * Create a new StoreCategoryDao with an attached configuration
     */
    public StoreCategoryDao(Configuration configuration) {
        super(StoreCategory.STORE_CATEGORY, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory.class, configuration);
    }

    @Override
    public Long getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory object) {
        return object.getStoreCategoryId();
    }

    /**
     * Fetch records that have <code>STORE_CATEGORY_ID BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfStoreCategoryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STORE_CATEGORY_ID IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByStoreCategoryId(Long... values) {
        return fetch(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>STORE_CATEGORY_ID = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory fetchOneByStoreCategoryId(Long value) {
        return fetchOne(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, value);
    }

    /**
     * Fetch a unique record that has <code>STORE_CATEGORY_ID = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchOptionalByStoreCategoryId(Long value) {
        return fetchOptional(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>CATEGORY_TYPE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfCategoryType(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CATEGORY_TYPE IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByCategoryType(String... values) {
        return fetch(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, values);
    }

    /**
     * Fetch a unique record that has <code>CATEGORY_TYPE = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory fetchOneByCategoryType(String value) {
        return fetchOne(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch a unique record that has <code>CATEGORY_TYPE = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchOptionalByCategoryType(String value) {
        return fetchOptional(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch records that have <code>CREATION_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreCategory.STORE_CATEGORY.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MODIFICATION_TIME IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreCategory.STORE_CATEGORY.MODIFICATION_TIME, values);
    }
}
