/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.daos;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreCategoryMap;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreCategoryMapRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryMapDao extends DAOImpl<StoreCategoryMapRecord, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap, UInteger> {

    /**
     * Create a new StoreCategoryMapDao without any configuration
     */
    public StoreCategoryMapDao() {
        super(StoreCategoryMap.STORE_CATEGORY_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap.class);
    }

    /**
     * Create a new StoreCategoryMapDao with an attached configuration
     */
    public StoreCategoryMapDao(Configuration configuration) {
        super(StoreCategoryMap.STORE_CATEGORY_MAP, com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap.class, configuration);
    }

    @Override
    public UInteger getId(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap object) {
        return object.getStoreCategoryMapId();
    }

    /**
     * Fetch records that have <code>store_category_map_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchRangeOfStoreCategoryMapId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_category_map_id IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchByStoreCategoryMapId(UInteger... values) {
        return fetch(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>store_category_map_id = value</code>
     */
    public com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap fetchOneByStoreCategoryMapId(UInteger value) {
        return fetchOne(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID, value);
    }

    /**
     * Fetch a unique record that has <code>store_category_map_id = value</code>
     */
    public Optional<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchOptionalByStoreCategoryMapId(UInteger value) {
        return fetchOptional(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID, value);
    }

    /**
     * Fetch records that have <code>store_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchRangeOfStoreId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchByStoreId(UInteger... values) {
        return fetch(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>store_category_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchRangeOfStoreCategoryId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_category_id IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchByStoreCategoryId(UInteger... values) {
        return fetch(StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreCategoryMap.STORE_CATEGORY_MAP.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreCategoryMap.STORE_CATEGORY_MAP.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreCategoryMap.STORE_CATEGORY_MAP.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreCategoryMap.STORE_CATEGORY_MAP.MODIFICATION_TIME, values);
    }
}
