/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables;


import ecommerceservice.dataaccesslayer.Catbirdnyc;
import ecommerceservice.dataaccesslayer.Indexes;
import ecommerceservice.dataaccesslayer.Keys;
import ecommerceservice.dataaccesslayer.tables.records.ProductTagMapRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagMap extends TableImpl<ProductTagMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.product_tag_map</code>
     */
    public static final ProductTagMap PRODUCT_TAG_MAP = new ProductTagMap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductTagMapRecord> getRecordType() {
        return ProductTagMapRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.product_tag_map.product_tag_map_id</code>.
     */
    public final TableField<ProductTagMapRecord, UInteger> PRODUCT_TAG_MAP_ID = createField(DSL.name("product_tag_map_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.product_tag_map.product_id</code>.
     */
    public final TableField<ProductTagMapRecord, UInteger> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product_tag_map.product_tag_id</code>.
     */
    public final TableField<ProductTagMapRecord, UInteger> PRODUCT_TAG_ID = createField(DSL.name("product_tag_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product_tag_map.creation_time</code>.
     */
    public final TableField<ProductTagMapRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.product_tag_map.modification_time</code>.
     */
    public final TableField<ProductTagMapRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private ProductTagMap(Name alias, Table<ProductTagMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductTagMap(Name alias, Table<ProductTagMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.product_tag_map</code> table reference
     */
    public ProductTagMap(String alias) {
        this(DSL.name(alias), PRODUCT_TAG_MAP);
    }

    /**
     * Create an aliased <code>Catbirdnyc.product_tag_map</code> table reference
     */
    public ProductTagMap(Name alias) {
        this(alias, PRODUCT_TAG_MAP);
    }

    /**
     * Create a <code>Catbirdnyc.product_tag_map</code> table reference
     */
    public ProductTagMap() {
        this(DSL.name("product_tag_map"), null);
    }

    public <O extends Record> ProductTagMap(Table<O> child, ForeignKey<O, ProductTagMapRecord> key) {
        super(child, key, PRODUCT_TAG_MAP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PRODUCT_TAG_MAP_PRODUCT_ID, Indexes.PRODUCT_TAG_MAP_PRODUCT_TAG_ID);
    }

    @Override
    public Identity<ProductTagMapRecord, UInteger> getIdentity() {
        return (Identity<ProductTagMapRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductTagMapRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_TAG_MAP_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProductTagMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_TAG_MAP_IBFK_1, Keys.PRODUCT_TAG_MAP_IBFK_2);
    }

    private transient Product _product;
    private transient ProductTag _productTag;

    /**
     * Get the implicit join path to the <code>Catbirdnyc.product</code> table.
     */
    public Product product() {
        if (_product == null)
            _product = new Product(this, Keys.PRODUCT_TAG_MAP_IBFK_1);

        return _product;
    }

    /**
     * Get the implicit join path to the <code>Catbirdnyc.product_tag</code>
     * table.
     */
    public ProductTag productTag() {
        if (_productTag == null)
            _productTag = new ProductTag(this, Keys.PRODUCT_TAG_MAP_IBFK_2);

        return _productTag;
    }

    @Override
    public ProductTagMap as(String alias) {
        return new ProductTagMap(DSL.name(alias), this);
    }

    @Override
    public ProductTagMap as(Name alias) {
        return new ProductTagMap(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTagMap rename(String name) {
        return new ProductTagMap(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTagMap rename(Name name) {
        return new ProductTagMap(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
