/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.pojos;


import org.jooq.types.UInteger;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      productBrandMapId;
    private UInteger      productId;
    private UInteger      productBrandId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductBrandMap() {}

    public ProductBrandMap(ProductBrandMap value) {
        this.productBrandMapId = value.productBrandMapId;
        this.productId = value.productId;
        this.productBrandId = value.productBrandId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductBrandMap(
        UInteger      productBrandMapId,
        UInteger      productId,
        UInteger      productBrandId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productBrandMapId = productBrandMapId;
        this.productId = productId;
        this.productBrandId = productBrandId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for
     * <code>Catbirdnyc.product_brand_map.product_brand_map_id</code>.
     */
    public UInteger getProductBrandMapId() {
        return this.productBrandMapId;
    }

    /**
     * Setter for
     * <code>Catbirdnyc.product_brand_map.product_brand_map_id</code>.
     */
    public void setProductBrandMapId(UInteger productBrandMapId) {
        this.productBrandMapId = productBrandMapId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand_map.product_id</code>.
     */
    public UInteger getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand_map.product_id</code>.
     */
    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand_map.product_brand_id</code>.
     */
    public UInteger getProductBrandId() {
        return this.productBrandId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand_map.product_brand_id</code>.
     */
    public void setProductBrandId(UInteger productBrandId) {
        this.productBrandId = productBrandId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand_map.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand_map.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand_map.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand_map.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductBrandMap (");

        sb.append(productBrandMapId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productBrandId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
