/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      productTagMapId;
    private UInteger      productId;
    private UInteger      productTagId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductTagMap() {}

    public ProductTagMap(ProductTagMap value) {
        this.productTagMapId = value.productTagMapId;
        this.productId = value.productId;
        this.productTagId = value.productTagId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductTagMap(
        UInteger      productTagMapId,
        UInteger      productId,
        UInteger      productTagId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productTagMapId = productTagMapId;
        this.productId = productId;
        this.productTagId = productTagId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.product_tag_map_id</code>.
     */
    public UInteger getProductTagMapId() {
        return this.productTagMapId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.product_tag_map_id</code>.
     */
    public void setProductTagMapId(UInteger productTagMapId) {
        this.productTagMapId = productTagMapId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.product_id</code>.
     */
    public UInteger getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.product_id</code>.
     */
    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.product_tag_id</code>.
     */
    public UInteger getProductTagId() {
        return this.productTagId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.product_tag_id</code>.
     */
    public void setProductTagId(UInteger productTagId) {
        this.productTagId = productTagId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_tag_map.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_tag_map.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductTagMap (");

        sb.append(productTagMapId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productTagId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
