/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.pojos;


import org.jooq.types.UInteger;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      productImageId;
    private UInteger      productId;
    private String        productImageLink;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductImage() {}

    public ProductImage(ProductImage value) {
        this.productImageId = value.productImageId;
        this.productId = value.productId;
        this.productImageLink = value.productImageLink;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductImage(
        UInteger      productImageId,
        UInteger      productId,
        String        productImageLink,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productImageId = productImageId;
        this.productId = productId;
        this.productImageLink = productImageLink;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.product_image_id</code>.
     */
    public UInteger getProductImageId() {
        return this.productImageId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.product_image_id</code>.
     */
    public void setProductImageId(UInteger productImageId) {
        this.productImageId = productImageId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.product_id</code>.
     */
    public UInteger getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.product_id</code>.
     */
    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.product_image_link</code>.
     */
    public String getProductImageLink() {
        return this.productImageLink;
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.product_image_link</code>.
     */
    public void setProductImageLink(String productImageLink) {
        this.productImageLink = productImageLink;
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_image.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_image.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductImage (");

        sb.append(productImageId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productImageLink);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
