/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrand implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      productBrandId;
    private String        brandName;
    private String        brandWebsite;
    private String        brandDescription;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductBrand() {}

    public ProductBrand(ProductBrand value) {
        this.productBrandId = value.productBrandId;
        this.brandName = value.brandName;
        this.brandWebsite = value.brandWebsite;
        this.brandDescription = value.brandDescription;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductBrand(
        UInteger      productBrandId,
        String        brandName,
        String        brandWebsite,
        String        brandDescription,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productBrandId = productBrandId;
        this.brandName = brandName;
        this.brandWebsite = brandWebsite;
        this.brandDescription = brandDescription;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.product_brand_id</code>.
     */
    public UInteger getProductBrandId() {
        return this.productBrandId;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.product_brand_id</code>.
     */
    public void setProductBrandId(UInteger productBrandId) {
        this.productBrandId = productBrandId;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.brand_name</code>.
     */
    public String getBrandName() {
        return this.brandName;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.brand_name</code>.
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.brand_website</code>.
     */
    public String getBrandWebsite() {
        return this.brandWebsite;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.brand_website</code>.
     */
    public void setBrandWebsite(String brandWebsite) {
        this.brandWebsite = brandWebsite;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.brand_description</code>.
     */
    public String getBrandDescription() {
        return this.brandDescription;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.brand_description</code>.
     */
    public void setBrandDescription(String brandDescription) {
        this.brandDescription = brandDescription;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.product_brand.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.product_brand.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductBrand (");

        sb.append(productBrandId);
        sb.append(", ").append(brandName);
        sb.append(", ").append(brandWebsite);
        sb.append(", ").append(brandDescription);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
