/*
 * This file is generated by jOOQ.
 */
package com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      storeCategoryMapId;
    private UInteger      storeId;
    private UInteger      storeCategoryId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreCategoryMap() {}

    public StoreCategoryMap(StoreCategoryMap value) {
        this.storeCategoryMapId = value.storeCategoryMapId;
        this.storeId = value.storeId;
        this.storeCategoryId = value.storeCategoryId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreCategoryMap(
        UInteger      storeCategoryMapId,
        UInteger      storeId,
        UInteger      storeCategoryId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeCategoryMapId = storeCategoryMapId;
        this.storeId = storeId;
        this.storeCategoryId = storeCategoryId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for
     * <code>Catbirdnyc.store_category_map.store_category_map_id</code>.
     */
    public UInteger getStoreCategoryMapId() {
        return this.storeCategoryMapId;
    }

    /**
     * Setter for
     * <code>Catbirdnyc.store_category_map.store_category_map_id</code>.
     */
    public void setStoreCategoryMapId(UInteger storeCategoryMapId) {
        this.storeCategoryMapId = storeCategoryMapId;
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.store_id</code>.
     */
    public UInteger getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.store_id</code>.
     */
    public void setStoreId(UInteger storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.store_category_id</code>.
     */
    public UInteger getStoreCategoryId() {
        return this.storeCategoryId;
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.store_category_id</code>.
     */
    public void setStoreCategoryId(UInteger storeCategoryId) {
        this.storeCategoryId = storeCategoryId;
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreCategoryMap (");

        sb.append(storeCategoryMapId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(storeCategoryId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
