/*
 * This file is generated by jOOQ.
 */
package com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.records;


import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.StoreCategoryMap;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryMapRecord extends UpdatableRecordImpl<StoreCategoryMapRecord> implements Record5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>Catbirdnyc.store_category_map.store_category_map_id</code>.
     */
    public void setStoreCategoryMapId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>Catbirdnyc.store_category_map.store_category_map_id</code>.
     */
    public UInteger getStoreCategoryMapId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.store_id</code>.
     */
    public void setStoreId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.store_id</code>.
     */
    public UInteger getStoreId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.store_category_id</code>.
     */
    public void setStoreCategoryId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.store_category_id</code>.
     */
    public UInteger getStoreCategoryId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Catbirdnyc.store_category_map.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Catbirdnyc.store_category_map.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.STORE_ID;
    }

    @Override
    public Field<UInteger> field3() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.MODIFICATION_TIME;
    }

    @Override
    public UInteger component1() {
        return getStoreCategoryMapId();
    }

    @Override
    public UInteger component2() {
        return getStoreId();
    }

    @Override
    public UInteger component3() {
        return getStoreCategoryId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModificationTime();
    }

    @Override
    public UInteger value1() {
        return getStoreCategoryMapId();
    }

    @Override
    public UInteger value2() {
        return getStoreId();
    }

    @Override
    public UInteger value3() {
        return getStoreCategoryId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModificationTime();
    }

    @Override
    public StoreCategoryMapRecord value1(UInteger value) {
        setStoreCategoryMapId(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value2(UInteger value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value3(UInteger value) {
        setStoreCategoryId(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value5(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord values(UInteger value1, UInteger value2, UInteger value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreCategoryMapRecord
     */
    public StoreCategoryMapRecord() {
        super(StoreCategoryMap.STORE_CATEGORY_MAP);
    }

    /**
     * Create a detached, initialised StoreCategoryMapRecord
     */
    public StoreCategoryMapRecord(UInteger storeCategoryMapId, UInteger storeId, UInteger storeCategoryId, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(StoreCategoryMap.STORE_CATEGORY_MAP);

        setStoreCategoryMapId(storeCategoryMapId);
        setStoreId(storeId);
        setStoreCategoryId(storeCategoryId);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreCategoryMapRecord
     */
    public StoreCategoryMapRecord(com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.pojos.StoreCategoryMap value) {
        super(StoreCategoryMap.STORE_CATEGORY_MAP);

        if (value != null) {
            setStoreCategoryMapId(value.getStoreCategoryMapId());
            setStoreId(value.getStoreId());
            setStoreCategoryId(value.getStoreCategoryId());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
