/*
 * This file is generated by jOOQ.
 */
package com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables;


import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.Catbirdnyc;
import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.Keys;
import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.records.ProductRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product extends TableImpl<ProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.product</code>
     */
    public static final Product PRODUCT = new Product();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductRecord> getRecordType() {
        return ProductRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.product.product_id</code>.
     */
    public final TableField<ProductRecord, UInteger> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.product.unique_product_name_in_store</code>.
     */
    public final TableField<ProductRecord, String> UNIQUE_PRODUCT_NAME_IN_STORE = createField(DSL.name("unique_product_name_in_store"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product.product_name</code>.
     */
    public final TableField<ProductRecord, String> PRODUCT_NAME = createField(DSL.name("product_name"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product.product_description</code>.
     */
    public final TableField<ProductRecord, String> PRODUCT_DESCRIPTION = createField(DSL.name("product_description"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product.price_in_dollar</code>.
     */
    public final TableField<ProductRecord, BigDecimal> PRICE_IN_DOLLAR = createField(DSL.name("price_in_dollar"), SQLDataType.DECIMAL(16, 2).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product.quantity</code>.
     */
    public final TableField<ProductRecord, UInteger> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>Catbirdnyc.product.store_id</code>.
     */
    public final TableField<ProductRecord, UInteger> STORE_ID = createField(DSL.name("store_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product.creation_time</code>.
     */
    public final TableField<ProductRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.product.modification_time</code>.
     */
    public final TableField<ProductRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private Product(Name alias, Table<ProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private Product(Name alias, Table<ProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.product</code> table reference
     */
    public Product(String alias) {
        this(DSL.name(alias), PRODUCT);
    }

    /**
     * Create an aliased <code>Catbirdnyc.product</code> table reference
     */
    public Product(Name alias) {
        this(alias, PRODUCT);
    }

    /**
     * Create a <code>Catbirdnyc.product</code> table reference
     */
    public Product() {
        this(DSL.name("product"), null);
    }

    public <O extends Record> Product(Table<O> child, ForeignKey<O, ProductRecord> key) {
        super(child, key, PRODUCT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public Identity<ProductRecord, UInteger> getIdentity() {
        return (Identity<ProductRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProductRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PRODUCT_UNIQUE_PRODUCT_NAME_IN_STORE);
    }

    @Override
    public List<ForeignKey<ProductRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PRODUCT_RT_STORE_RC_STORE_ID);
    }

    private transient Store _store;

    /**
     * Get the implicit join path to the <code>Catbirdnyc.store</code> table.
     */
    public Store store() {
        if (_store == null)
            _store = new Store(this, Keys.FK_PRODUCT_RT_STORE_RC_STORE_ID);

        return _store;
    }

    @Override
    public Product as(String alias) {
        return new Product(DSL.name(alias), this);
    }

    @Override
    public Product as(Name alias) {
        return new Product(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(String name) {
        return new Product(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Name name) {
        return new Product(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<UInteger, String, String, String, BigDecimal, UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
