/*
 * This file is generated by jOOQ.
 */
package com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables;


import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.Catbirdnyc;
import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.Indexes;
import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.Keys;
import com.bimelogye.CommerceService.eCommerceServiceDataAccessLayer.tables.records.ProductImageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductImage extends TableImpl<ProductImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.product_image</code>
     */
    public static final ProductImage PRODUCT_IMAGE = new ProductImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductImageRecord> getRecordType() {
        return ProductImageRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.product_image.product_image_id</code>.
     */
    public final TableField<ProductImageRecord, UInteger> PRODUCT_IMAGE_ID = createField(DSL.name("product_image_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.product_image.product_id</code>.
     */
    public final TableField<ProductImageRecord, UInteger> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product_image.product_image_link</code>.
     */
    public final TableField<ProductImageRecord, String> PRODUCT_IMAGE_LINK = createField(DSL.name("product_image_link"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product_image.creation_time</code>.
     */
    public final TableField<ProductImageRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.product_image.modification_time</code>.
     */
    public final TableField<ProductImageRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private ProductImage(Name alias, Table<ProductImageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductImage(Name alias, Table<ProductImageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.product_image</code> table reference
     */
    public ProductImage(String alias) {
        this(DSL.name(alias), PRODUCT_IMAGE);
    }

    /**
     * Create an aliased <code>Catbirdnyc.product_image</code> table reference
     */
    public ProductImage(Name alias) {
        this(alias, PRODUCT_IMAGE);
    }

    /**
     * Create a <code>Catbirdnyc.product_image</code> table reference
     */
    public ProductImage() {
        this(DSL.name("product_image"), null);
    }

    public <O extends Record> ProductImage(Table<O> child, ForeignKey<O, ProductImageRecord> key) {
        super(child, key, PRODUCT_IMAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PRODUCT_IMAGE_PRODUCT_ID);
    }

    @Override
    public Identity<ProductImageRecord, UInteger> getIdentity() {
        return (Identity<ProductImageRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductImageRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_IMAGE_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProductImageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_IMAGE_IBFK_1);
    }

    private transient Product _product;

    /**
     * Get the implicit join path to the <code>Catbirdnyc.product</code> table.
     */
    public Product product() {
        if (_product == null)
            _product = new Product(this, Keys.PRODUCT_IMAGE_IBFK_1);

        return _product;
    }

    @Override
    public ProductImage as(String alias) {
        return new ProductImage(DSL.name(alias), this);
    }

    @Override
    public ProductImage as(Name alias) {
        return new ProductImage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductImage rename(String name) {
        return new ProductImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductImage rename(Name name) {
        return new ProductImage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
