/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.DefaultSchema;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductBrandRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrand extends TableImpl<ProductBrandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PRODUCT_BRAND</code>
     */
    public static final ProductBrand PRODUCT_BRAND = new ProductBrand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductBrandRecord> getRecordType() {
        return ProductBrandRecord.class;
    }

    /**
     * The column <code>PRODUCT_BRAND.PRODUCT_BRAND_ID</code>.
     */
    public final TableField<ProductBrandRecord, Long> PRODUCT_BRAND_ID = createField(DSL.name("PRODUCT_BRAND_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PRODUCT_BRAND.BRAND_NAME</code>.
     */
    public final TableField<ProductBrandRecord, String> BRAND_NAME = createField(DSL.name("BRAND_NAME"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>PRODUCT_BRAND.BRAND_WEBSITE</code>.
     */
    public final TableField<ProductBrandRecord, String> BRAND_WEBSITE = createField(DSL.name("BRAND_WEBSITE"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>PRODUCT_BRAND.BRAND_DESCRIPTION</code>.
     */
    public final TableField<ProductBrandRecord, String> BRAND_DESCRIPTION = createField(DSL.name("BRAND_DESCRIPTION"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>PRODUCT_BRAND.CREATION_TIME</code>.
     */
    public final TableField<ProductBrandRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("CREATION_TIME"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PRODUCT_BRAND.MODIFICATION_TIME</code>.
     */
    public final TableField<ProductBrandRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("MODIFICATION_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    private ProductBrand(Name alias, Table<ProductBrandRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductBrand(Name alias, Table<ProductBrandRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PRODUCT_BRAND</code> table reference
     */
    public ProductBrand(String alias) {
        this(DSL.name(alias), PRODUCT_BRAND);
    }

    /**
     * Create an aliased <code>PRODUCT_BRAND</code> table reference
     */
    public ProductBrand(Name alias) {
        this(alias, PRODUCT_BRAND);
    }

    /**
     * Create a <code>PRODUCT_BRAND</code> table reference
     */
    public ProductBrand() {
        this(DSL.name("PRODUCT_BRAND"), null);
    }

    public <O extends Record> ProductBrand(Table<O> child, ForeignKey<O, ProductBrandRecord> key) {
        super(child, key, PRODUCT_BRAND);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ProductBrandRecord, Long> getIdentity() {
        return (Identity<ProductBrandRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductBrandRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_42;
    }

    @Override
    public ProductBrand as(String alias) {
        return new ProductBrand(DSL.name(alias), this);
    }

    @Override
    public ProductBrand as(Name alias) {
        return new ProductBrand(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductBrand rename(String name) {
        return new ProductBrand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductBrand rename(Name name) {
        return new ProductBrand(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
