/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.DefaultSchema;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductTagRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTag extends TableImpl<ProductTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PRODUCT_TAG</code>
     */
    public static final ProductTag PRODUCT_TAG = new ProductTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductTagRecord> getRecordType() {
        return ProductTagRecord.class;
    }

    /**
     * The column <code>PRODUCT_TAG.PRODUCT_TAG_ID</code>.
     */
    public final TableField<ProductTagRecord, Long> PRODUCT_TAG_ID = createField(DSL.name("PRODUCT_TAG_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PRODUCT_TAG.TAG_CONTENT</code>.
     */
    public final TableField<ProductTagRecord, String> TAG_CONTENT = createField(DSL.name("TAG_CONTENT"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>PRODUCT_TAG.CREATION_TIME</code>.
     */
    public final TableField<ProductTagRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("CREATION_TIME"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PRODUCT_TAG.MODIFICATION_TIME</code>.
     */
    public final TableField<ProductTagRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("MODIFICATION_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    private ProductTag(Name alias, Table<ProductTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductTag(Name alias, Table<ProductTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PRODUCT_TAG</code> table reference
     */
    public ProductTag(String alias) {
        this(DSL.name(alias), PRODUCT_TAG);
    }

    /**
     * Create an aliased <code>PRODUCT_TAG</code> table reference
     */
    public ProductTag(Name alias) {
        this(alias, PRODUCT_TAG);
    }

    /**
     * Create a <code>PRODUCT_TAG</code> table reference
     */
    public ProductTag() {
        this(DSL.name("PRODUCT_TAG"), null);
    }

    public <O extends Record> ProductTag(Table<O> child, ForeignKey<O, ProductTagRecord> key) {
        super(child, key, PRODUCT_TAG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ProductTagRecord, Long> getIdentity() {
        return (Identity<ProductTagRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductTagRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public ProductTag as(String alias) {
        return new ProductTag(DSL.name(alias), this);
    }

    @Override
    public ProductTag as(Name alias) {
        return new ProductTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTag rename(String name) {
        return new ProductTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTag rename(Name name) {
        return new ProductTag(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
