/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.DefaultSchema;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductCategoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory extends TableImpl<ProductCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PRODUCT_CATEGORY</code>
     */
    public static final ProductCategory PRODUCT_CATEGORY = new ProductCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductCategoryRecord> getRecordType() {
        return ProductCategoryRecord.class;
    }

    /**
     * The column <code>PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID</code>.
     */
    public final TableField<ProductCategoryRecord, Long> PRODUCT_CATEGORY_ID = createField(DSL.name("PRODUCT_CATEGORY_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PRODUCT_CATEGORY.CATEGORY_TYPE</code>.
     */
    public final TableField<ProductCategoryRecord, String> CATEGORY_TYPE = createField(DSL.name("CATEGORY_TYPE"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>PRODUCT_CATEGORY.CREATION_TIME</code>.
     */
    public final TableField<ProductCategoryRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("CREATION_TIME"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PRODUCT_CATEGORY.MODIFICATION_TIME</code>.
     */
    public final TableField<ProductCategoryRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("MODIFICATION_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    private ProductCategory(Name alias, Table<ProductCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductCategory(Name alias, Table<ProductCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PRODUCT_CATEGORY</code> table reference
     */
    public ProductCategory(String alias) {
        this(DSL.name(alias), PRODUCT_CATEGORY);
    }

    /**
     * Create an aliased <code>PRODUCT_CATEGORY</code> table reference
     */
    public ProductCategory(Name alias) {
        this(alias, PRODUCT_CATEGORY);
    }

    /**
     * Create a <code>PRODUCT_CATEGORY</code> table reference
     */
    public ProductCategory() {
        this(DSL.name("PRODUCT_CATEGORY"), null);
    }

    public <O extends Record> ProductCategory(Table<O> child, ForeignKey<O, ProductCategoryRecord> key) {
        super(child, key, PRODUCT_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ProductCategoryRecord, Long> getIdentity() {
        return (Identity<ProductCategoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductCategoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    public List<UniqueKey<ProductCategoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_PRODUCT_CATEGORY_C_CATEGORY_TYPE);
    }

    @Override
    public ProductCategory as(String alias) {
        return new ProductCategory(DSL.name(alias), this);
    }

    @Override
    public ProductCategory as(Name alias) {
        return new ProductCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategory rename(String name) {
        return new ProductCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategory rename(Name name) {
        return new ProductCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
