/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.DefaultSchema;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductImageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductImage extends TableImpl<ProductImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PRODUCT_IMAGE</code>
     */
    public static final ProductImage PRODUCT_IMAGE = new ProductImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductImageRecord> getRecordType() {
        return ProductImageRecord.class;
    }

    /**
     * The column <code>PRODUCT_IMAGE.PRODUCT_IMAGE_ID</code>.
     */
    public final TableField<ProductImageRecord, Long> PRODUCT_IMAGE_ID = createField(DSL.name("PRODUCT_IMAGE_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PRODUCT_IMAGE.PRODUCT_ID</code>.
     */
    public final TableField<ProductImageRecord, Long> PRODUCT_ID = createField(DSL.name("PRODUCT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PRODUCT_IMAGE.PRODUCT_IMAGE_LINK</code>.
     */
    public final TableField<ProductImageRecord, String> PRODUCT_IMAGE_LINK = createField(DSL.name("PRODUCT_IMAGE_LINK"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>PRODUCT_IMAGE.CREATION_TIME</code>.
     */
    public final TableField<ProductImageRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("CREATION_TIME"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PRODUCT_IMAGE.MODIFICATION_TIME</code>.
     */
    public final TableField<ProductImageRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("MODIFICATION_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    private ProductImage(Name alias, Table<ProductImageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductImage(Name alias, Table<ProductImageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PRODUCT_IMAGE</code> table reference
     */
    public ProductImage(String alias) {
        this(DSL.name(alias), PRODUCT_IMAGE);
    }

    /**
     * Create an aliased <code>PRODUCT_IMAGE</code> table reference
     */
    public ProductImage(Name alias) {
        this(alias, PRODUCT_IMAGE);
    }

    /**
     * Create a <code>PRODUCT_IMAGE</code> table reference
     */
    public ProductImage() {
        this(DSL.name("PRODUCT_IMAGE"), null);
    }

    public <O extends Record> ProductImage(Table<O> child, ForeignKey<O, ProductImageRecord> key) {
        super(child, key, PRODUCT_IMAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ProductImageRecord, Long> getIdentity() {
        return (Identity<ProductImageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductImageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_426;
    }

    @Override
    public List<ForeignKey<ProductImageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_4266);
    }

    private transient Product _product;

    /**
     * Get the implicit join path to the <code>PUBLIC.PRODUCT</code> table.
     */
    public Product product() {
        if (_product == null)
            _product = new Product(this, Keys.CONSTRAINT_4266);

        return _product;
    }

    @Override
    public ProductImage as(String alias) {
        return new ProductImage(DSL.name(alias), this);
    }

    @Override
    public ProductImage as(Name alias) {
        return new ProductImage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductImage rename(String name) {
        return new ProductImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductImage rename(Name name) {
        return new ProductImage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
