/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.Catbirdnyc;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.ProductBrandMapRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandMap extends TableImpl<ProductBrandMapRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.product_brand_map</code>
     */
    public static final ProductBrandMap PRODUCT_BRAND_MAP = new ProductBrandMap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductBrandMapRecord> getRecordType() {
        return ProductBrandMapRecord.class;
    }

    /**
     * The column
     * <code>Catbirdnyc.product_brand_map.product_brand_map_id</code>.
     */
    public final TableField<ProductBrandMapRecord, UInteger> PRODUCT_BRAND_MAP_ID = createField(DSL.name("product_brand_map_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.product_brand_map.product_id</code>.
     */
    public final TableField<ProductBrandMapRecord, UInteger> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product_brand_map.product_brand_id</code>.
     */
    public final TableField<ProductBrandMapRecord, UInteger> PRODUCT_BRAND_ID = createField(DSL.name("product_brand_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.product_brand_map.creation_time</code>.
     */
    public final TableField<ProductBrandMapRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.product_brand_map.modification_time</code>.
     */
    public final TableField<ProductBrandMapRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private ProductBrandMap(Name alias, Table<ProductBrandMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductBrandMap(Name alias, Table<ProductBrandMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.product_brand_map</code> table
     * reference
     */
    public ProductBrandMap(String alias) {
        this(DSL.name(alias), PRODUCT_BRAND_MAP);
    }

    /**
     * Create an aliased <code>Catbirdnyc.product_brand_map</code> table
     * reference
     */
    public ProductBrandMap(Name alias) {
        this(alias, PRODUCT_BRAND_MAP);
    }

    /**
     * Create a <code>Catbirdnyc.product_brand_map</code> table reference
     */
    public ProductBrandMap() {
        this(DSL.name("product_brand_map"), null);
    }

    public <O extends Record> ProductBrandMap(Table<O> child, ForeignKey<O, ProductBrandMapRecord> key) {
        super(child, key, PRODUCT_BRAND_MAP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public Identity<ProductBrandMapRecord, UInteger> getIdentity() {
        return (Identity<ProductBrandMapRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductBrandMapRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_BRAND_MAP_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProductBrandMapRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PRODUCT_BRAND_MAP_RT_PRODUCT_RC_PRODUCT_ID, Keys.FK_PRODUCT_BRAND_MAP_RT_PRODUCT_BRAND_RC_PRODUCT_BRAND_ID);
    }

    private transient Product _product;
    private transient ProductBrand _productBrand;

    /**
     * Get the implicit join path to the <code>Catbirdnyc.product</code> table.
     */
    public Product product() {
        if (_product == null)
            _product = new Product(this, Keys.FK_PRODUCT_BRAND_MAP_RT_PRODUCT_RC_PRODUCT_ID);

        return _product;
    }

    /**
     * Get the implicit join path to the <code>Catbirdnyc.product_brand</code>
     * table.
     */
    public ProductBrand productBrand() {
        if (_productBrand == null)
            _productBrand = new ProductBrand(this, Keys.FK_PRODUCT_BRAND_MAP_RT_PRODUCT_BRAND_RC_PRODUCT_BRAND_ID);

        return _productBrand;
    }

    @Override
    public ProductBrandMap as(String alias) {
        return new ProductBrandMap(DSL.name(alias), this);
    }

    @Override
    public ProductBrandMap as(Name alias) {
        return new ProductBrandMap(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductBrandMap rename(String name) {
        return new ProductBrandMap(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductBrandMap rename(Name name) {
        return new ProductBrandMap(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
