/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.Catbirdnyc;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreLocationRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreLocation extends TableImpl<StoreLocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.store_location</code>
     */
    public static final StoreLocation STORE_LOCATION = new StoreLocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreLocationRecord> getRecordType() {
        return StoreLocationRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.store_location.store_location_id</code>.
     */
    public final TableField<StoreLocationRecord, UInteger> STORE_LOCATION_ID = createField(DSL.name("store_location_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.store_location.store_id</code>.
     */
    public final TableField<StoreLocationRecord, UInteger> STORE_ID = createField(DSL.name("store_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_location.formatted_address</code>.
     */
    public final TableField<StoreLocationRecord, String> FORMATTED_ADDRESS = createField(DSL.name("formatted_address"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_location.latitude</code>.
     */
    public final TableField<StoreLocationRecord, BigDecimal> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DECIMAL(10, 6).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_location.longitude</code>.
     */
    public final TableField<StoreLocationRecord, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DECIMAL(10, 6).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_location.creation_time</code>.
     */
    public final TableField<StoreLocationRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.store_location.modification_time</code>.
     */
    public final TableField<StoreLocationRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private StoreLocation(Name alias, Table<StoreLocationRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoreLocation(Name alias, Table<StoreLocationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.store_location</code> table reference
     */
    public StoreLocation(String alias) {
        this(DSL.name(alias), STORE_LOCATION);
    }

    /**
     * Create an aliased <code>Catbirdnyc.store_location</code> table reference
     */
    public StoreLocation(Name alias) {
        this(alias, STORE_LOCATION);
    }

    /**
     * Create a <code>Catbirdnyc.store_location</code> table reference
     */
    public StoreLocation() {
        this(DSL.name("store_location"), null);
    }

    public <O extends Record> StoreLocation(Table<O> child, ForeignKey<O, StoreLocationRecord> key) {
        super(child, key, STORE_LOCATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public Identity<StoreLocationRecord, UInteger> getIdentity() {
        return (Identity<StoreLocationRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoreLocationRecord> getPrimaryKey() {
        return Keys.KEY_STORE_LOCATION_PRIMARY;
    }

    @Override
    public List<ForeignKey<StoreLocationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_STORE_LOCATION_RT_STORE_RC_STORE_ID);
    }

    private transient Store _store;

    /**
     * Get the implicit join path to the <code>Catbirdnyc.store</code> table.
     */
    public Store store() {
        if (_store == null)
            _store = new Store(this, Keys.FK_STORE_LOCATION_RT_STORE_RC_STORE_ID);

        return _store;
    }

    @Override
    public StoreLocation as(String alias) {
        return new StoreLocation(DSL.name(alias), this);
    }

    @Override
    public StoreLocation as(Name alias) {
        return new StoreLocation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreLocation rename(String name) {
        return new StoreLocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreLocation rename(Name name) {
        return new StoreLocation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UInteger, UInteger, String, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
