/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables;


import com.bimelody.ecommerceservice.dataaccesslayer.DefaultSchema;
import com.bimelody.ecommerceservice.dataaccesslayer.Keys;
import com.bimelody.ecommerceservice.dataaccesslayer.tables.records.StoreImageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreImage extends TableImpl<StoreImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STORE_IMAGE</code>
     */
    public static final StoreImage STORE_IMAGE = new StoreImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreImageRecord> getRecordType() {
        return StoreImageRecord.class;
    }

    /**
     * The column <code>STORE_IMAGE.STORE_IMAGE_ID</code>.
     */
    public final TableField<StoreImageRecord, Long> STORE_IMAGE_ID = createField(DSL.name("STORE_IMAGE_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>STORE_IMAGE.STORE_ID</code>.
     */
    public final TableField<StoreImageRecord, Long> STORE_ID = createField(DSL.name("STORE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>STORE_IMAGE.STORE_IMAGE_LINK</code>.
     */
    public final TableField<StoreImageRecord, String> STORE_IMAGE_LINK = createField(DSL.name("STORE_IMAGE_LINK"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>STORE_IMAGE.CREATION_TIME</code>.
     */
    public final TableField<StoreImageRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("CREATION_TIME"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>STORE_IMAGE.MODIFICATION_TIME</code>.
     */
    public final TableField<StoreImageRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("MODIFICATION_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    private StoreImage(Name alias, Table<StoreImageRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoreImage(Name alias, Table<StoreImageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STORE_IMAGE</code> table reference
     */
    public StoreImage(String alias) {
        this(DSL.name(alias), STORE_IMAGE);
    }

    /**
     * Create an aliased <code>STORE_IMAGE</code> table reference
     */
    public StoreImage(Name alias) {
        this(alias, STORE_IMAGE);
    }

    /**
     * Create a <code>STORE_IMAGE</code> table reference
     */
    public StoreImage() {
        this(DSL.name("STORE_IMAGE"), null);
    }

    public <O extends Record> StoreImage(Table<O> child, ForeignKey<O, StoreImageRecord> key) {
        super(child, key, STORE_IMAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<StoreImageRecord, Long> getIdentity() {
        return (Identity<StoreImageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoreImageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5D;
    }

    @Override
    public List<ForeignKey<StoreImageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_STORE_IMAGE_RT_STORE_RC_STORE_ID);
    }

    private transient Store _store;

    /**
     * Get the implicit join path to the <code>PUBLIC.STORE</code> table.
     */
    public Store store() {
        if (_store == null)
            _store = new Store(this, Keys.FK_STORE_IMAGE_RT_STORE_RC_STORE_ID);

        return _store;
    }

    @Override
    public StoreImage as(String alias) {
        return new StoreImage(DSL.name(alias), this);
    }

    @Override
    public StoreImage as(Name alias) {
        return new StoreImage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreImage rename(String name) {
        return new StoreImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreImage rename(Name name) {
        return new StoreImage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
