/*
 * This file is generated by jOOQ.
 */
package com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables;


import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.Catbirdnyc;
import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.Keys;
import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.records.CustomerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer extends TableImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.customer</code>
     */
    public static final Customer CUSTOMER = new Customer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerRecord> getRecordType() {
        return CustomerRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.customer.customer_id</code>.
     */
    public final TableField<CustomerRecord, UInteger> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.customer.cognito_user_id</code>.
     */
    public final TableField<CustomerRecord, String> COGNITO_USER_ID = createField(DSL.name("cognito_user_id"), SQLDataType.VARCHAR(96), this, "");

    /**
     * The column <code>Catbirdnyc.customer.cognito_user_pool_id</code>.
     */
    public final TableField<CustomerRecord, String> COGNITO_USER_POOL_ID = createField(DSL.name("cognito_user_pool_id"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>Catbirdnyc.customer.email</code>.
     */
    public final TableField<CustomerRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.customer.phone_number</code>.
     */
    public final TableField<CustomerRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.customer.username</code>.
     */
    public final TableField<CustomerRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.customer.profile_picture_link</code>.
     */
    public final TableField<CustomerRecord, String> PROFILE_PICTURE_LINK = createField(DSL.name("profile_picture_link"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>Catbirdnyc.customer.is_banned</code>.
     */
    public final TableField<CustomerRecord, Byte> IS_BANNED = createField(DSL.name("is_banned"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>Catbirdnyc.customer.creation_time</code>.
     */
    public final TableField<CustomerRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.customer.modification_time</code>.
     */
    public final TableField<CustomerRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private Customer(Name alias, Table<CustomerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Customer(Name alias, Table<CustomerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.customer</code> table reference
     */
    public Customer(String alias) {
        this(DSL.name(alias), CUSTOMER);
    }

    /**
     * Create an aliased <code>Catbirdnyc.customer</code> table reference
     */
    public Customer(Name alias) {
        this(alias, CUSTOMER);
    }

    /**
     * Create a <code>Catbirdnyc.customer</code> table reference
     */
    public Customer() {
        this(DSL.name("customer"), null);
    }

    public <O extends Record> Customer(Table<O> child, ForeignKey<O, CustomerRecord> key) {
        super(child, key, CUSTOMER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public Identity<CustomerRecord, UInteger> getIdentity() {
        return (Identity<CustomerRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomerRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMER_PRIMARY;
    }

    @Override
    public List<UniqueKey<CustomerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CUSTOMER_COGNITO_USER_ID, Keys.KEY_CUSTOMER_EMAIL, Keys.KEY_CUSTOMER_USERNAME);
    }

    @Override
    public Customer as(String alias) {
        return new Customer(DSL.name(alias), this);
    }

    @Override
    public Customer as(Name alias) {
        return new Customer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(String name) {
        return new Customer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(Name name) {
        return new Customer(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<UInteger, String, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
