/*
 * This file is generated by jOOQ.
 */
package com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables;


import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.Catbirdnyc;
import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.Keys;
import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.records.StoreCategoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategory extends TableImpl<StoreCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc.store_category</code>
     */
    public static final StoreCategory STORE_CATEGORY = new StoreCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreCategoryRecord> getRecordType() {
        return StoreCategoryRecord.class;
    }

    /**
     * The column <code>Catbirdnyc.store_category.store_category_id</code>.
     */
    public final TableField<StoreCategoryRecord, UInteger> STORE_CATEGORY_ID = createField(DSL.name("store_category_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>Catbirdnyc.store_category.category_type</code>.
     */
    public final TableField<StoreCategoryRecord, String> CATEGORY_TYPE = createField(DSL.name("category_type"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>Catbirdnyc.store_category.creation_time</code>.
     */
    public final TableField<StoreCategoryRecord, LocalDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>Catbirdnyc.store_category.modification_time</code>.
     */
    public final TableField<StoreCategoryRecord, LocalDateTime> MODIFICATION_TIME = createField(DSL.name("modification_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private StoreCategory(Name alias, Table<StoreCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoreCategory(Name alias, Table<StoreCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Catbirdnyc.store_category</code> table reference
     */
    public StoreCategory(String alias) {
        this(DSL.name(alias), STORE_CATEGORY);
    }

    /**
     * Create an aliased <code>Catbirdnyc.store_category</code> table reference
     */
    public StoreCategory(Name alias) {
        this(alias, STORE_CATEGORY);
    }

    /**
     * Create a <code>Catbirdnyc.store_category</code> table reference
     */
    public StoreCategory() {
        this(DSL.name("store_category"), null);
    }

    public <O extends Record> StoreCategory(Table<O> child, ForeignKey<O, StoreCategoryRecord> key) {
        super(child, key, STORE_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Catbirdnyc.CATBIRDNYC;
    }

    @Override
    public Identity<StoreCategoryRecord, UInteger> getIdentity() {
        return (Identity<StoreCategoryRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoreCategoryRecord> getPrimaryKey() {
        return Keys.KEY_STORE_CATEGORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<StoreCategoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_STORE_CATEGORY_CATEGORY_TYPE);
    }

    @Override
    public StoreCategory as(String alias) {
        return new StoreCategory(DSL.name(alias), this);
    }

    @Override
    public StoreCategory as(Name alias) {
        return new StoreCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreCategory rename(String name) {
        return new StoreCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreCategory rename(Name name) {
        return new StoreCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
