/*
 * This file is generated by jOOQ.
 */
package com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.daos;


import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.ProductTag;
import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.records.ProductTagRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagDao extends DAOImpl<ProductTagRecord, com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag, UInteger> {

    /**
     * Create a new ProductTagDao without any configuration
     */
    public ProductTagDao() {
        super(ProductTag.PRODUCT_TAG, com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag.class);
    }

    /**
     * Create a new ProductTagDao with an attached configuration
     */
    public ProductTagDao(Configuration configuration) {
        super(ProductTag.PRODUCT_TAG, com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag.class, configuration);
    }

    @Override
    public UInteger getId(com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag object) {
        return object.getProductTagId();
    }

    /**
     * Fetch records that have <code>product_tag_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchRangeOfProductTagId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(ProductTag.PRODUCT_TAG.PRODUCT_TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_tag_id IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchByProductTagId(UInteger... values) {
        return fetch(ProductTag.PRODUCT_TAG.PRODUCT_TAG_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_tag_id = value</code>
     */
    public com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag fetchOneByProductTagId(UInteger value) {
        return fetchOne(ProductTag.PRODUCT_TAG.PRODUCT_TAG_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_tag_id = value</code>
     */
    public Optional<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchOptionalByProductTagId(UInteger value) {
        return fetchOptional(ProductTag.PRODUCT_TAG.PRODUCT_TAG_ID, value);
    }

    /**
     * Fetch records that have <code>tag_content BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchRangeOfTagContent(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductTag.PRODUCT_TAG.TAG_CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tag_content IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchByTagContent(String... values) {
        return fetch(ProductTag.PRODUCT_TAG.TAG_CONTENT, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductTag.PRODUCT_TAG.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchByCreationTime(LocalDateTime... values) {
        return fetch(ProductTag.PRODUCT_TAG.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductTag.PRODUCT_TAG.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.ProductTag> fetchByModificationTime(LocalDateTime... values) {
        return fetch(ProductTag.PRODUCT_TAG.MODIFICATION_TIME, values);
    }
}
