/*
 * This file is generated by jOOQ.
 */
package com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.daos;


import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.Store;
import com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.records.StoreRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreDao extends DAOImpl<StoreRecord, com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store, UInteger> {

    /**
     * Create a new StoreDao without any configuration
     */
    public StoreDao() {
        super(Store.STORE, com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store.class);
    }

    /**
     * Create a new StoreDao with an attached configuration
     */
    public StoreDao(Configuration configuration) {
        super(Store.STORE, com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store.class, configuration);
    }

    @Override
    public UInteger getId(com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store object) {
        return object.getStoreId();
    }

    /**
     * Fetch records that have <code>store_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfStoreId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Store.STORE.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByStoreId(UInteger... values) {
        return fetch(Store.STORE.STORE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>store_id = value</code>
     */
    public com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store fetchOneByStoreId(UInteger value) {
        return fetchOne(Store.STORE.STORE_ID, value);
    }

    /**
     * Fetch a unique record that has <code>store_id = value</code>
     */
    public Optional<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchOptionalByStoreId(UInteger value) {
        return fetchOptional(Store.STORE.STORE_ID, value);
    }

    /**
     * Fetch records that have <code>unique_store_name BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfUniqueStoreName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.UNIQUE_STORE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>unique_store_name IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByUniqueStoreName(String... values) {
        return fetch(Store.STORE.UNIQUE_STORE_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>unique_store_name = value</code>
     */
    public com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store fetchOneByUniqueStoreName(String value) {
        return fetchOne(Store.STORE.UNIQUE_STORE_NAME, value);
    }

    /**
     * Fetch a unique record that has <code>unique_store_name = value</code>
     */
    public Optional<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchOptionalByUniqueStoreName(String value) {
        return fetchOptional(Store.STORE.UNIQUE_STORE_NAME, value);
    }

    /**
     * Fetch records that have <code>store_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfStoreName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.STORE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_name IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByStoreName(String... values) {
        return fetch(Store.STORE.STORE_NAME, values);
    }

    /**
     * Fetch records that have <code>store_website BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfStoreWebsite(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.STORE_WEBSITE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_website IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByStoreWebsite(String... values) {
        return fetch(Store.STORE.STORE_WEBSITE, values);
    }

    /**
     * Fetch records that have <code>store_description BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfStoreDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.STORE_DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_description IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByStoreDescription(String... values) {
        return fetch(Store.STORE.STORE_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>contact_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfContactNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.CONTACT_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>contact_number IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByContactNumber(String... values) {
        return fetch(Store.STORE.CONTACT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>contact_email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfContactEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.CONTACT_EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>contact_email IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByContactEmail(String... values) {
        return fetch(Store.STORE.CONTACT_EMAIL, values);
    }

    /**
     * Fetch records that have <code>store_cover_image BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfStoreCoverImage(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.STORE_COVER_IMAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_cover_image IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByStoreCoverImage(String... values) {
        return fetch(Store.STORE.STORE_COVER_IMAGE, values);
    }

    /**
     * Fetch records that have <code>yelp_link BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfYelpLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.YELP_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>yelp_link IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByYelpLink(String... values) {
        return fetch(Store.STORE.YELP_LINK, values);
    }

    /**
     * Fetch records that have <code>facebook_link BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfFacebookLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.FACEBOOK_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>facebook_link IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByFacebookLink(String... values) {
        return fetch(Store.STORE.FACEBOOK_LINK, values);
    }

    /**
     * Fetch records that have <code>instagram_link BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfInstagramLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.INSTAGRAM_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>instagram_link IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByInstagramLink(String... values) {
        return fetch(Store.STORE.INSTAGRAM_LINK, values);
    }

    /**
     * Fetch records that have <code>twitter_link BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfTwitterLink(String lowerInclusive, String upperInclusive) {
        return fetchRange(Store.STORE.TWITTER_LINK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>twitter_link IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByTwitterLink(String... values) {
        return fetch(Store.STORE.TWITTER_LINK, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Store.STORE.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByCreationTime(LocalDateTime... values) {
        return fetch(Store.STORE.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Store.STORE.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<com.bimelody.eCommerceService.eCommerceServiceDataAccessLayer.tables.pojos.Store> fetchByModificationTime(LocalDateTime... values) {
        return fetch(Store.STORE.MODIFICATION_TIME, values);
    }
}
