/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.daos;


import ecommerceservice.dataaccesslayer.tables.Product;
import ecommerceservice.dataaccesslayer.tables.records.ProductRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductDao extends DAOImpl<ProductRecord, ecommerceservice.dataaccesslayer.tables.pojos.Product, UInteger> {

    /**
     * Create a new ProductDao without any configuration
     */
    public ProductDao() {
        super(Product.PRODUCT, ecommerceservice.dataaccesslayer.tables.pojos.Product.class);
    }

    /**
     * Create a new ProductDao with an attached configuration
     */
    public ProductDao(Configuration configuration) {
        super(Product.PRODUCT, ecommerceservice.dataaccesslayer.tables.pojos.Product.class, configuration);
    }

    @Override
    public UInteger getId(ecommerceservice.dataaccesslayer.tables.pojos.Product object) {
        return object.getProductId();
    }

    /**
     * Fetch records that have <code>product_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfProductId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Product.PRODUCT.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_id IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByProductId(UInteger... values) {
        return fetch(Product.PRODUCT.PRODUCT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_id = value</code>
     */
    public ecommerceservice.dataaccesslayer.tables.pojos.Product fetchOneByProductId(UInteger value) {
        return fetchOne(Product.PRODUCT.PRODUCT_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_id = value</code>
     */
    public Optional<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchOptionalByProductId(UInteger value) {
        return fetchOptional(Product.PRODUCT.PRODUCT_ID, value);
    }

    /**
     * Fetch records that have <code>unique_product_name_in_store BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfUniqueProductNameInStore(String lowerInclusive, String upperInclusive) {
        return fetchRange(Product.PRODUCT.UNIQUE_PRODUCT_NAME_IN_STORE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>unique_product_name_in_store IN
     * (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByUniqueProductNameInStore(String... values) {
        return fetch(Product.PRODUCT.UNIQUE_PRODUCT_NAME_IN_STORE, values);
    }

    /**
     * Fetch records that have <code>product_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfProductName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Product.PRODUCT.PRODUCT_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_name IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByProductName(String... values) {
        return fetch(Product.PRODUCT.PRODUCT_NAME, values);
    }

    /**
     * Fetch records that have <code>product_description BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfProductDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Product.PRODUCT.PRODUCT_DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_description IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByProductDescription(String... values) {
        return fetch(Product.PRODUCT.PRODUCT_DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>price_in_dollar BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfPriceInDollar(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Product.PRODUCT.PRICE_IN_DOLLAR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price_in_dollar IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByPriceInDollar(BigDecimal... values) {
        return fetch(Product.PRODUCT.PRICE_IN_DOLLAR, values);
    }

    /**
     * Fetch records that have <code>quantity BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfQuantity(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Product.PRODUCT.QUANTITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByQuantity(UInteger... values) {
        return fetch(Product.PRODUCT.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>store_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfStoreId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(Product.PRODUCT.STORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByStoreId(UInteger... values) {
        return fetch(Product.PRODUCT.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Product.PRODUCT.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByCreationTime(LocalDateTime... values) {
        return fetch(Product.PRODUCT.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Product.PRODUCT.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.Product> fetchByModificationTime(LocalDateTime... values) {
        return fetch(Product.PRODUCT.MODIFICATION_TIME, values);
    }
}
