/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer.tables.daos;


import ecommerceservice.dataaccesslayer.tables.StoreCategory;
import ecommerceservice.dataaccesslayer.tables.records.StoreCategoryRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryDao extends DAOImpl<StoreCategoryRecord, ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory, UInteger> {

    /**
     * Create a new StoreCategoryDao without any configuration
     */
    public StoreCategoryDao() {
        super(StoreCategory.STORE_CATEGORY, ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory.class);
    }

    /**
     * Create a new StoreCategoryDao with an attached configuration
     */
    public StoreCategoryDao(Configuration configuration) {
        super(StoreCategory.STORE_CATEGORY, ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory.class, configuration);
    }

    @Override
    public UInteger getId(ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory object) {
        return object.getStoreCategoryId();
    }

    /**
     * Fetch records that have <code>store_category_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfStoreCategoryId(UInteger lowerInclusive, UInteger upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>store_category_id IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByStoreCategoryId(UInteger... values) {
        return fetch(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>store_category_id = value</code>
     */
    public ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory fetchOneByStoreCategoryId(UInteger value) {
        return fetchOne(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, value);
    }

    /**
     * Fetch a unique record that has <code>store_category_id = value</code>
     */
    public Optional<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchOptionalByStoreCategoryId(UInteger value) {
        return fetchOptional(StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>category_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfCategoryType(String lowerInclusive, String upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category_type IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByCategoryType(String... values) {
        return fetch(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, values);
    }

    /**
     * Fetch a unique record that has <code>category_type = value</code>
     */
    public ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory fetchOneByCategoryType(String value) {
        return fetchOne(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch a unique record that has <code>category_type = value</code>
     */
    public Optional<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchOptionalByCategoryType(String value) {
        return fetchOptional(StoreCategory.STORE_CATEGORY.CATEGORY_TYPE, value);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfCreationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByCreationTime(LocalDateTime... values) {
        return fetch(StoreCategory.STORE_CATEGORY.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>modification_time BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchRangeOfModificationTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(StoreCategory.STORE_CATEGORY.MODIFICATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modification_time IN (values)</code>
     */
    public List<ecommerceservice.dataaccesslayer.tables.pojos.StoreCategory> fetchByModificationTime(LocalDateTime... values) {
        return fetch(StoreCategory.STORE_CATEGORY.MODIFICATION_TIME, values);
    }
}
