/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer;


import ecommerceservice.dataaccesslayer.tables.Customer;
import ecommerceservice.dataaccesslayer.tables.Product;
import ecommerceservice.dataaccesslayer.tables.ProductBrand;
import ecommerceservice.dataaccesslayer.tables.ProductBrandMap;
import ecommerceservice.dataaccesslayer.tables.ProductCategory;
import ecommerceservice.dataaccesslayer.tables.ProductCategoryMap;
import ecommerceservice.dataaccesslayer.tables.ProductImage;
import ecommerceservice.dataaccesslayer.tables.ProductTag;
import ecommerceservice.dataaccesslayer.tables.ProductTagMap;
import ecommerceservice.dataaccesslayer.tables.Store;
import ecommerceservice.dataaccesslayer.tables.StoreCategory;
import ecommerceservice.dataaccesslayer.tables.StoreCategoryMap;
import ecommerceservice.dataaccesslayer.tables.StoreImage;
import ecommerceservice.dataaccesslayer.tables.StoreLocation;
import ecommerceservice.dataaccesslayer.tables.StoreOwner;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Catbirdnyc extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Catbirdnyc</code>
     */
    public static final Catbirdnyc CATBIRDNYC = new Catbirdnyc();

    /**
     * The table <code>Catbirdnyc.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>Catbirdnyc.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>Catbirdnyc.product_brand</code>.
     */
    public final ProductBrand PRODUCT_BRAND = ProductBrand.PRODUCT_BRAND;

    /**
     * The table <code>Catbirdnyc.product_brand_map</code>.
     */
    public final ProductBrandMap PRODUCT_BRAND_MAP = ProductBrandMap.PRODUCT_BRAND_MAP;

    /**
     * The table <code>Catbirdnyc.product_category</code>.
     */
    public final ProductCategory PRODUCT_CATEGORY = ProductCategory.PRODUCT_CATEGORY;

    /**
     * The table <code>Catbirdnyc.product_category_map</code>.
     */
    public final ProductCategoryMap PRODUCT_CATEGORY_MAP = ProductCategoryMap.PRODUCT_CATEGORY_MAP;

    /**
     * The table <code>Catbirdnyc.product_image</code>.
     */
    public final ProductImage PRODUCT_IMAGE = ProductImage.PRODUCT_IMAGE;

    /**
     * The table <code>Catbirdnyc.product_tag</code>.
     */
    public final ProductTag PRODUCT_TAG = ProductTag.PRODUCT_TAG;

    /**
     * The table <code>Catbirdnyc.product_tag_map</code>.
     */
    public final ProductTagMap PRODUCT_TAG_MAP = ProductTagMap.PRODUCT_TAG_MAP;

    /**
     * The table <code>Catbirdnyc.store</code>.
     */
    public final Store STORE = Store.STORE;

    /**
     * The table <code>Catbirdnyc.store_category</code>.
     */
    public final StoreCategory STORE_CATEGORY = StoreCategory.STORE_CATEGORY;

    /**
     * The table <code>Catbirdnyc.store_category_map</code>.
     */
    public final StoreCategoryMap STORE_CATEGORY_MAP = StoreCategoryMap.STORE_CATEGORY_MAP;

    /**
     * The table <code>Catbirdnyc.store_image</code>.
     */
    public final StoreImage STORE_IMAGE = StoreImage.STORE_IMAGE;

    /**
     * The table <code>Catbirdnyc.store_location</code>.
     */
    public final StoreLocation STORE_LOCATION = StoreLocation.STORE_LOCATION;

    /**
     * The table <code>Catbirdnyc.store_owner</code>.
     */
    public final StoreOwner STORE_OWNER = StoreOwner.STORE_OWNER;

    /**
     * No further instances allowed
     */
    private Catbirdnyc() {
        super("Catbirdnyc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Customer.CUSTOMER,
            Product.PRODUCT,
            ProductBrand.PRODUCT_BRAND,
            ProductBrandMap.PRODUCT_BRAND_MAP,
            ProductCategory.PRODUCT_CATEGORY,
            ProductCategoryMap.PRODUCT_CATEGORY_MAP,
            ProductImage.PRODUCT_IMAGE,
            ProductTag.PRODUCT_TAG,
            ProductTagMap.PRODUCT_TAG_MAP,
            Store.STORE,
            StoreCategory.STORE_CATEGORY,
            StoreCategoryMap.STORE_CATEGORY_MAP,
            StoreImage.STORE_IMAGE,
            StoreLocation.STORE_LOCATION,
            StoreOwner.STORE_OWNER
        );
    }
}
