/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer;


import ecommerceservice.dataaccesslayer.tables.ProductImage;
import ecommerceservice.dataaccesslayer.tables.ProductTagMap;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in Catbirdnyc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRODUCT_IMAGE_PRODUCT_ID = Internal.createIndex(DSL.name("product_id"), ProductImage.PRODUCT_IMAGE, new OrderField[] { ProductImage.PRODUCT_IMAGE.PRODUCT_ID }, false);
    public static final Index PRODUCT_TAG_MAP_PRODUCT_ID = Internal.createIndex(DSL.name("product_id"), ProductTagMap.PRODUCT_TAG_MAP, new OrderField[] { ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID }, false);
    public static final Index PRODUCT_TAG_MAP_PRODUCT_TAG_ID = Internal.createIndex(DSL.name("product_tag_id"), ProductTagMap.PRODUCT_TAG_MAP, new OrderField[] { ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID }, false);
}
