/*
 * This file is generated by jOOQ.
 */
package ecommerceservice.dataaccesslayer;


import ecommerceservice.dataaccesslayer.tables.Customer;
import ecommerceservice.dataaccesslayer.tables.Product;
import ecommerceservice.dataaccesslayer.tables.ProductBrand;
import ecommerceservice.dataaccesslayer.tables.ProductBrandMap;
import ecommerceservice.dataaccesslayer.tables.ProductCategory;
import ecommerceservice.dataaccesslayer.tables.ProductCategoryMap;
import ecommerceservice.dataaccesslayer.tables.ProductImage;
import ecommerceservice.dataaccesslayer.tables.ProductTag;
import ecommerceservice.dataaccesslayer.tables.ProductTagMap;
import ecommerceservice.dataaccesslayer.tables.Store;
import ecommerceservice.dataaccesslayer.tables.StoreCategory;
import ecommerceservice.dataaccesslayer.tables.StoreCategoryMap;
import ecommerceservice.dataaccesslayer.tables.StoreImage;
import ecommerceservice.dataaccesslayer.tables.StoreLocation;
import ecommerceservice.dataaccesslayer.tables.StoreOwner;


/**
 * Convenience access to all tables in Catbirdnyc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Catbirdnyc.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>Catbirdnyc.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>Catbirdnyc.product_brand</code>.
     */
    public static final ProductBrand PRODUCT_BRAND = ProductBrand.PRODUCT_BRAND;

    /**
     * The table <code>Catbirdnyc.product_brand_map</code>.
     */
    public static final ProductBrandMap PRODUCT_BRAND_MAP = ProductBrandMap.PRODUCT_BRAND_MAP;

    /**
     * The table <code>Catbirdnyc.product_category</code>.
     */
    public static final ProductCategory PRODUCT_CATEGORY = ProductCategory.PRODUCT_CATEGORY;

    /**
     * The table <code>Catbirdnyc.product_category_map</code>.
     */
    public static final ProductCategoryMap PRODUCT_CATEGORY_MAP = ProductCategoryMap.PRODUCT_CATEGORY_MAP;

    /**
     * The table <code>Catbirdnyc.product_image</code>.
     */
    public static final ProductImage PRODUCT_IMAGE = ProductImage.PRODUCT_IMAGE;

    /**
     * The table <code>Catbirdnyc.product_tag</code>.
     */
    public static final ProductTag PRODUCT_TAG = ProductTag.PRODUCT_TAG;

    /**
     * The table <code>Catbirdnyc.product_tag_map</code>.
     */
    public static final ProductTagMap PRODUCT_TAG_MAP = ProductTagMap.PRODUCT_TAG_MAP;

    /**
     * The table <code>Catbirdnyc.store</code>.
     */
    public static final Store STORE = Store.STORE;

    /**
     * The table <code>Catbirdnyc.store_category</code>.
     */
    public static final StoreCategory STORE_CATEGORY = StoreCategory.STORE_CATEGORY;

    /**
     * The table <code>Catbirdnyc.store_category_map</code>.
     */
    public static final StoreCategoryMap STORE_CATEGORY_MAP = StoreCategoryMap.STORE_CATEGORY_MAP;

    /**
     * The table <code>Catbirdnyc.store_image</code>.
     */
    public static final StoreImage STORE_IMAGE = StoreImage.STORE_IMAGE;

    /**
     * The table <code>Catbirdnyc.store_location</code>.
     */
    public static final StoreLocation STORE_LOCATION = StoreLocation.STORE_LOCATION;

    /**
     * The table <code>Catbirdnyc.store_owner</code>.
     */
    public static final StoreOwner STORE_OWNER = StoreOwner.STORE_OWNER;
}
