/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.records;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.Product;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record9<Long, String, String, String, BigDecimal, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PRODUCT.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PRODUCT.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PRODUCT.UNIQUE_PRODUCT_NAME_IN_STORE</code>.
     */
    public void setUniqueProductNameInStore(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PRODUCT.UNIQUE_PRODUCT_NAME_IN_STORE</code>.
     */
    public String getUniqueProductNameInStore() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PRODUCT.PRODUCT_NAME</code>.
     */
    public void setProductName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PRODUCT.PRODUCT_NAME</code>.
     */
    public String getProductName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PRODUCT.PRODUCT_DESCRIPTION</code>.
     */
    public void setProductDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PRODUCT.PRODUCT_DESCRIPTION</code>.
     */
    public String getProductDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PRODUCT.PRICE_IN_DOLLAR</code>.
     */
    public void setPriceInDollar(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PRODUCT.PRICE_IN_DOLLAR</code>.
     */
    public BigDecimal getPriceInDollar() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>PRODUCT.QUANTITY</code>.
     */
    public void setQuantity(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>PRODUCT.QUANTITY</code>.
     */
    public Long getQuantity() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PRODUCT.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>PRODUCT.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>PRODUCT.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>PRODUCT.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>PRODUCT.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>PRODUCT.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, BigDecimal, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, BigDecimal, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Product.PRODUCT.PRODUCT_ID;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.UNIQUE_PRODUCT_NAME_IN_STORE;
    }

    @Override
    public Field<String> field3() {
        return Product.PRODUCT.PRODUCT_NAME;
    }

    @Override
    public Field<String> field4() {
        return Product.PRODUCT.PRODUCT_DESCRIPTION;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Product.PRODUCT.PRICE_IN_DOLLAR;
    }

    @Override
    public Field<Long> field6() {
        return Product.PRODUCT.QUANTITY;
    }

    @Override
    public Field<Long> field7() {
        return Product.PRODUCT.STORE_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Product.PRODUCT.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Product.PRODUCT.MODIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getProductId();
    }

    @Override
    public String component2() {
        return getUniqueProductNameInStore();
    }

    @Override
    public String component3() {
        return getProductName();
    }

    @Override
    public String component4() {
        return getProductDescription();
    }

    @Override
    public BigDecimal component5() {
        return getPriceInDollar();
    }

    @Override
    public Long component6() {
        return getQuantity();
    }

    @Override
    public Long component7() {
        return getStoreId();
    }

    @Override
    public LocalDateTime component8() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component9() {
        return getModificationTime();
    }

    @Override
    public Long value1() {
        return getProductId();
    }

    @Override
    public String value2() {
        return getUniqueProductNameInStore();
    }

    @Override
    public String value3() {
        return getProductName();
    }

    @Override
    public String value4() {
        return getProductDescription();
    }

    @Override
    public BigDecimal value5() {
        return getPriceInDollar();
    }

    @Override
    public Long value6() {
        return getQuantity();
    }

    @Override
    public Long value7() {
        return getStoreId();
    }

    @Override
    public LocalDateTime value8() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value9() {
        return getModificationTime();
    }

    @Override
    public ProductRecord value1(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setUniqueProductNameInStore(value);
        return this;
    }

    @Override
    public ProductRecord value3(String value) {
        setProductName(value);
        return this;
    }

    @Override
    public ProductRecord value4(String value) {
        setProductDescription(value);
        return this;
    }

    @Override
    public ProductRecord value5(BigDecimal value) {
        setPriceInDollar(value);
        return this;
    }

    @Override
    public ProductRecord value6(Long value) {
        setQuantity(value);
        return this;
    }

    @Override
    public ProductRecord value7(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public ProductRecord value8(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProductRecord value9(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public ProductRecord values(Long value1, String value2, String value3, String value4, BigDecimal value5, Long value6, Long value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Long productId, String uniqueProductNameInStore, String productName, String productDescription, BigDecimal priceInDollar, Long quantity, Long storeId, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(Product.PRODUCT);

        setProductId(productId);
        setUniqueProductNameInStore(uniqueProductNameInStore);
        setProductName(productName);
        setProductDescription(productDescription);
        setPriceInDollar(priceInDollar);
        setQuantity(quantity);
        setStoreId(storeId);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Product value) {
        super(Product.PRODUCT);

        if (value != null) {
            setProductId(value.getProductId());
            setUniqueProductNameInStore(value.getUniqueProductNameInStore());
            setProductName(value.getProductName());
            setProductDescription(value.getProductDescription());
            setPriceInDollar(value.getPriceInDollar());
            setQuantity(value.getQuantity());
            setStoreId(value.getStoreId());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
