/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.records;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductBrandMap;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandMapRecord extends UpdatableRecordImpl<ProductBrandMapRecord> implements Record5<Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID</code>.
     */
    public void setProductBrandMapId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID</code>.
     */
    public Long getProductBrandMapId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID</code>.
     */
    public void setProductBrandId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID</code>.
     */
    public Long getProductBrandId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID;
    }

    @Override
    public Field<Long> field2() {
        return ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_ID;
    }

    @Override
    public Field<Long> field3() {
        return ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProductBrandMap.PRODUCT_BRAND_MAP.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ProductBrandMap.PRODUCT_BRAND_MAP.MODIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getProductBrandMapId();
    }

    @Override
    public Long component2() {
        return getProductId();
    }

    @Override
    public Long component3() {
        return getProductBrandId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModificationTime();
    }

    @Override
    public Long value1() {
        return getProductBrandMapId();
    }

    @Override
    public Long value2() {
        return getProductId();
    }

    @Override
    public Long value3() {
        return getProductBrandId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModificationTime();
    }

    @Override
    public ProductBrandMapRecord value1(Long value) {
        setProductBrandMapId(value);
        return this;
    }

    @Override
    public ProductBrandMapRecord value2(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductBrandMapRecord value3(Long value) {
        setProductBrandId(value);
        return this;
    }

    @Override
    public ProductBrandMapRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProductBrandMapRecord value5(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public ProductBrandMapRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductBrandMapRecord
     */
    public ProductBrandMapRecord() {
        super(ProductBrandMap.PRODUCT_BRAND_MAP);
    }

    /**
     * Create a detached, initialised ProductBrandMapRecord
     */
    public ProductBrandMapRecord(Long productBrandMapId, Long productId, Long productBrandId, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(ProductBrandMap.PRODUCT_BRAND_MAP);

        setProductBrandMapId(productBrandMapId);
        setProductId(productId);
        setProductBrandId(productBrandId);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised ProductBrandMapRecord
     */
    public ProductBrandMapRecord(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductBrandMap value) {
        super(ProductBrandMap.PRODUCT_BRAND_MAP);

        if (value != null) {
            setProductBrandMapId(value.getProductBrandMapId());
            setProductId(value.getProductId());
            setProductBrandId(value.getProductBrandId());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
