/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.records;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.ProductCategory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryRecord extends UpdatableRecordImpl<ProductCategoryRecord> implements Record4<Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID</code>.
     */
    public void setProductCategoryId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID</code>.
     */
    public Long getProductCategoryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.CATEGORY_TYPE</code>.
     */
    public void setCategoryType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.CATEGORY_TYPE</code>.
     */
    public String getCategoryType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID;
    }

    @Override
    public Field<String> field2() {
        return ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ProductCategory.PRODUCT_CATEGORY.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProductCategory.PRODUCT_CATEGORY.MODIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getProductCategoryId();
    }

    @Override
    public String component2() {
        return getCategoryType();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component4() {
        return getModificationTime();
    }

    @Override
    public Long value1() {
        return getProductCategoryId();
    }

    @Override
    public String value2() {
        return getCategoryType();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value4() {
        return getModificationTime();
    }

    @Override
    public ProductCategoryRecord value1(Long value) {
        setProductCategoryId(value);
        return this;
    }

    @Override
    public ProductCategoryRecord value2(String value) {
        setCategoryType(value);
        return this;
    }

    @Override
    public ProductCategoryRecord value3(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ProductCategoryRecord value4(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public ProductCategoryRecord values(Long value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductCategoryRecord
     */
    public ProductCategoryRecord() {
        super(ProductCategory.PRODUCT_CATEGORY);
    }

    /**
     * Create a detached, initialised ProductCategoryRecord
     */
    public ProductCategoryRecord(Long productCategoryId, String categoryType, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(ProductCategory.PRODUCT_CATEGORY);

        setProductCategoryId(productCategoryId);
        setCategoryType(categoryType);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised ProductCategoryRecord
     */
    public ProductCategoryRecord(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.ProductCategory value) {
        super(ProductCategory.PRODUCT_CATEGORY);

        if (value != null) {
            setProductCategoryId(value.getProductCategoryId());
            setCategoryType(value.getCategoryType());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
