/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.records;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreCategoryMap;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryMapRecord extends UpdatableRecordImpl<StoreCategoryMapRecord> implements Record5<Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID</code>.
     */
    public void setStoreCategoryMapId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID</code>.
     */
    public Long getStoreCategoryMapId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_ID</code>.
     */
    public void setStoreCategoryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_ID</code>.
     */
    public Long getStoreCategoryId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID;
    }

    @Override
    public Field<Long> field2() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.STORE_ID;
    }

    @Override
    public Field<Long> field3() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return StoreCategoryMap.STORE_CATEGORY_MAP.MODIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getStoreCategoryMapId();
    }

    @Override
    public Long component2() {
        return getStoreId();
    }

    @Override
    public Long component3() {
        return getStoreCategoryId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModificationTime();
    }

    @Override
    public Long value1() {
        return getStoreCategoryMapId();
    }

    @Override
    public Long value2() {
        return getStoreId();
    }

    @Override
    public Long value3() {
        return getStoreCategoryId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModificationTime();
    }

    @Override
    public StoreCategoryMapRecord value1(Long value) {
        setStoreCategoryMapId(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value2(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value3(Long value) {
        setStoreCategoryId(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value4(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord value5(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreCategoryMapRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreCategoryMapRecord
     */
    public StoreCategoryMapRecord() {
        super(StoreCategoryMap.STORE_CATEGORY_MAP);
    }

    /**
     * Create a detached, initialised StoreCategoryMapRecord
     */
    public StoreCategoryMapRecord(Long storeCategoryMapId, Long storeId, Long storeCategoryId, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(StoreCategoryMap.STORE_CATEGORY_MAP);

        setStoreCategoryMapId(storeCategoryMapId);
        setStoreId(storeId);
        setStoreCategoryId(storeCategoryId);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreCategoryMapRecord
     */
    public StoreCategoryMapRecord(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreCategoryMap value) {
        super(StoreCategoryMap.STORE_CATEGORY_MAP);

        if (value != null) {
            setStoreCategoryMapId(value.getStoreCategoryMapId());
            setStoreId(value.getStoreId());
            setStoreCategoryId(value.getStoreCategoryId());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
