/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.records;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.Store;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreRecord extends UpdatableRecordImpl<StoreRecord> implements Record14<Long, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STORE.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STORE.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STORE.UNIQUE_STORE_NAME</code>.
     */
    public void setUniqueStoreName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>STORE.UNIQUE_STORE_NAME</code>.
     */
    public String getUniqueStoreName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>STORE.CONTACT_NUMBER</code>.
     */
    public void setContactNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>STORE.CONTACT_NUMBER</code>.
     */
    public String getContactNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>STORE.CONTACT_EMAIL</code>.
     */
    public void setContactEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>STORE.CONTACT_EMAIL</code>.
     */
    public String getContactEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>STORE.STORE_NAME</code>.
     */
    public void setStoreName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>STORE.STORE_NAME</code>.
     */
    public String getStoreName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>STORE.STORE_WEBSITE</code>.
     */
    public void setStoreWebsite(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>STORE.STORE_WEBSITE</code>.
     */
    public String getStoreWebsite() {
        return (String) get(5);
    }

    /**
     * Setter for <code>STORE.STORE_DESCRIPTION</code>.
     */
    public void setStoreDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>STORE.STORE_DESCRIPTION</code>.
     */
    public String getStoreDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>STORE.STORE_COVER_IMAGE</code>.
     */
    public void setStoreCoverImage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>STORE.STORE_COVER_IMAGE</code>.
     */
    public String getStoreCoverImage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>STORE.YELP_LINK</code>.
     */
    public void setYelpLink(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>STORE.YELP_LINK</code>.
     */
    public String getYelpLink() {
        return (String) get(8);
    }

    /**
     * Setter for <code>STORE.FACEBOOK_LINK</code>.
     */
    public void setFacebookLink(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>STORE.FACEBOOK_LINK</code>.
     */
    public String getFacebookLink() {
        return (String) get(9);
    }

    /**
     * Setter for <code>STORE.INSTAGRAM_LINK</code>.
     */
    public void setInstagramLink(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>STORE.INSTAGRAM_LINK</code>.
     */
    public String getInstagramLink() {
        return (String) get(10);
    }

    /**
     * Setter for <code>STORE.TWITTER_LINK</code>.
     */
    public void setTwitterLink(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>STORE.TWITTER_LINK</code>.
     */
    public String getTwitterLink() {
        return (String) get(11);
    }

    /**
     * Setter for <code>STORE.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>STORE.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>STORE.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>STORE.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Store.STORE.STORE_ID;
    }

    @Override
    public Field<String> field2() {
        return Store.STORE.UNIQUE_STORE_NAME;
    }

    @Override
    public Field<String> field3() {
        return Store.STORE.CONTACT_NUMBER;
    }

    @Override
    public Field<String> field4() {
        return Store.STORE.CONTACT_EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Store.STORE.STORE_NAME;
    }

    @Override
    public Field<String> field6() {
        return Store.STORE.STORE_WEBSITE;
    }

    @Override
    public Field<String> field7() {
        return Store.STORE.STORE_DESCRIPTION;
    }

    @Override
    public Field<String> field8() {
        return Store.STORE.STORE_COVER_IMAGE;
    }

    @Override
    public Field<String> field9() {
        return Store.STORE.YELP_LINK;
    }

    @Override
    public Field<String> field10() {
        return Store.STORE.FACEBOOK_LINK;
    }

    @Override
    public Field<String> field11() {
        return Store.STORE.INSTAGRAM_LINK;
    }

    @Override
    public Field<String> field12() {
        return Store.STORE.TWITTER_LINK;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Store.STORE.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return Store.STORE.MODIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getStoreId();
    }

    @Override
    public String component2() {
        return getUniqueStoreName();
    }

    @Override
    public String component3() {
        return getContactNumber();
    }

    @Override
    public String component4() {
        return getContactEmail();
    }

    @Override
    public String component5() {
        return getStoreName();
    }

    @Override
    public String component6() {
        return getStoreWebsite();
    }

    @Override
    public String component7() {
        return getStoreDescription();
    }

    @Override
    public String component8() {
        return getStoreCoverImage();
    }

    @Override
    public String component9() {
        return getYelpLink();
    }

    @Override
    public String component10() {
        return getFacebookLink();
    }

    @Override
    public String component11() {
        return getInstagramLink();
    }

    @Override
    public String component12() {
        return getTwitterLink();
    }

    @Override
    public LocalDateTime component13() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component14() {
        return getModificationTime();
    }

    @Override
    public Long value1() {
        return getStoreId();
    }

    @Override
    public String value2() {
        return getUniqueStoreName();
    }

    @Override
    public String value3() {
        return getContactNumber();
    }

    @Override
    public String value4() {
        return getContactEmail();
    }

    @Override
    public String value5() {
        return getStoreName();
    }

    @Override
    public String value6() {
        return getStoreWebsite();
    }

    @Override
    public String value7() {
        return getStoreDescription();
    }

    @Override
    public String value8() {
        return getStoreCoverImage();
    }

    @Override
    public String value9() {
        return getYelpLink();
    }

    @Override
    public String value10() {
        return getFacebookLink();
    }

    @Override
    public String value11() {
        return getInstagramLink();
    }

    @Override
    public String value12() {
        return getTwitterLink();
    }

    @Override
    public LocalDateTime value13() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value14() {
        return getModificationTime();
    }

    @Override
    public StoreRecord value1(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreRecord value2(String value) {
        setUniqueStoreName(value);
        return this;
    }

    @Override
    public StoreRecord value3(String value) {
        setContactNumber(value);
        return this;
    }

    @Override
    public StoreRecord value4(String value) {
        setContactEmail(value);
        return this;
    }

    @Override
    public StoreRecord value5(String value) {
        setStoreName(value);
        return this;
    }

    @Override
    public StoreRecord value6(String value) {
        setStoreWebsite(value);
        return this;
    }

    @Override
    public StoreRecord value7(String value) {
        setStoreDescription(value);
        return this;
    }

    @Override
    public StoreRecord value8(String value) {
        setStoreCoverImage(value);
        return this;
    }

    @Override
    public StoreRecord value9(String value) {
        setYelpLink(value);
        return this;
    }

    @Override
    public StoreRecord value10(String value) {
        setFacebookLink(value);
        return this;
    }

    @Override
    public StoreRecord value11(String value) {
        setInstagramLink(value);
        return this;
    }

    @Override
    public StoreRecord value12(String value) {
        setTwitterLink(value);
        return this;
    }

    @Override
    public StoreRecord value13(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreRecord value14(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreRecord
     */
    public StoreRecord() {
        super(Store.STORE);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(Long storeId, String uniqueStoreName, String contactNumber, String contactEmail, String storeName, String storeWebsite, String storeDescription, String storeCoverImage, String yelpLink, String facebookLink, String instagramLink, String twitterLink, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(Store.STORE);

        setStoreId(storeId);
        setUniqueStoreName(uniqueStoreName);
        setContactNumber(contactNumber);
        setContactEmail(contactEmail);
        setStoreName(storeName);
        setStoreWebsite(storeWebsite);
        setStoreDescription(storeDescription);
        setStoreCoverImage(storeCoverImage);
        setYelpLink(yelpLink);
        setFacebookLink(facebookLink);
        setInstagramLink(instagramLink);
        setTwitterLink(twitterLink);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.Store value) {
        super(Store.STORE);

        if (value != null) {
            setStoreId(value.getStoreId());
            setUniqueStoreName(value.getUniqueStoreName());
            setContactNumber(value.getContactNumber());
            setContactEmail(value.getContactEmail());
            setStoreName(value.getStoreName());
            setStoreWebsite(value.getStoreWebsite());
            setStoreDescription(value.getStoreDescription());
            setStoreCoverImage(value.getStoreCoverImage());
            setYelpLink(value.getYelpLink());
            setFacebookLink(value.getFacebookLink());
            setInstagramLink(value.getInstagramLink());
            setTwitterLink(value.getTwitterLink());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
