/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.records;


import com.bimelody.ecommerceservice.dataaccesslayer.tables.StoreOwner;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreOwnerRecord extends UpdatableRecordImpl<StoreOwnerRecord> implements Record11<Long, Long, String, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STORE_OWNER.STORE_OWNER_ID</code>.
     */
    public void setStoreOwnerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STORE_OWNER.STORE_OWNER_ID</code>.
     */
    public Long getStoreOwnerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STORE_OWNER.STORE_ID</code>.
     */
    public void setStoreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>STORE_OWNER.STORE_ID</code>.
     */
    public Long getStoreId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>STORE_OWNER.COGNITO_USER_ID</code>.
     */
    public void setCognitoUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>STORE_OWNER.COGNITO_USER_ID</code>.
     */
    public String getCognitoUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>STORE_OWNER.COGNITO_USER_POOL_ID</code>.
     */
    public void setCognitoUserPoolId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>STORE_OWNER.COGNITO_USER_POOL_ID</code>.
     */
    public String getCognitoUserPoolId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>STORE_OWNER.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>STORE_OWNER.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>STORE_OWNER.PHONE_NUMBER</code>.
     */
    public void setPhoneNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>STORE_OWNER.PHONE_NUMBER</code>.
     */
    public String getPhoneNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>STORE_OWNER.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>STORE_OWNER.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(6);
    }

    /**
     * Setter for <code>STORE_OWNER.PROFILE_PICTURE_LINK</code>.
     */
    public void setProfilePictureLink(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>STORE_OWNER.PROFILE_PICTURE_LINK</code>.
     */
    public String getProfilePictureLink() {
        return (String) get(7);
    }

    /**
     * Setter for <code>STORE_OWNER.IS_BANNED</code>.
     */
    public void setIsBanned(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>STORE_OWNER.IS_BANNED</code>.
     */
    public Boolean getIsBanned() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>STORE_OWNER.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>STORE_OWNER.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>STORE_OWNER.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>STORE_OWNER.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, String, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, String, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StoreOwner.STORE_OWNER.STORE_OWNER_ID;
    }

    @Override
    public Field<Long> field2() {
        return StoreOwner.STORE_OWNER.STORE_ID;
    }

    @Override
    public Field<String> field3() {
        return StoreOwner.STORE_OWNER.COGNITO_USER_ID;
    }

    @Override
    public Field<String> field4() {
        return StoreOwner.STORE_OWNER.COGNITO_USER_POOL_ID;
    }

    @Override
    public Field<String> field5() {
        return StoreOwner.STORE_OWNER.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return StoreOwner.STORE_OWNER.PHONE_NUMBER;
    }

    @Override
    public Field<String> field7() {
        return StoreOwner.STORE_OWNER.USERNAME;
    }

    @Override
    public Field<String> field8() {
        return StoreOwner.STORE_OWNER.PROFILE_PICTURE_LINK;
    }

    @Override
    public Field<Boolean> field9() {
        return StoreOwner.STORE_OWNER.IS_BANNED;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return StoreOwner.STORE_OWNER.CREATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return StoreOwner.STORE_OWNER.MODIFICATION_TIME;
    }

    @Override
    public Long component1() {
        return getStoreOwnerId();
    }

    @Override
    public Long component2() {
        return getStoreId();
    }

    @Override
    public String component3() {
        return getCognitoUserId();
    }

    @Override
    public String component4() {
        return getCognitoUserPoolId();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getPhoneNumber();
    }

    @Override
    public String component7() {
        return getUsername();
    }

    @Override
    public String component8() {
        return getProfilePictureLink();
    }

    @Override
    public Boolean component9() {
        return getIsBanned();
    }

    @Override
    public LocalDateTime component10() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime component11() {
        return getModificationTime();
    }

    @Override
    public Long value1() {
        return getStoreOwnerId();
    }

    @Override
    public Long value2() {
        return getStoreId();
    }

    @Override
    public String value3() {
        return getCognitoUserId();
    }

    @Override
    public String value4() {
        return getCognitoUserPoolId();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getPhoneNumber();
    }

    @Override
    public String value7() {
        return getUsername();
    }

    @Override
    public String value8() {
        return getProfilePictureLink();
    }

    @Override
    public Boolean value9() {
        return getIsBanned();
    }

    @Override
    public LocalDateTime value10() {
        return getCreationTime();
    }

    @Override
    public LocalDateTime value11() {
        return getModificationTime();
    }

    @Override
    public StoreOwnerRecord value1(Long value) {
        setStoreOwnerId(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value2(Long value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value3(String value) {
        setCognitoUserId(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value4(String value) {
        setCognitoUserPoolId(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value6(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value7(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value8(String value) {
        setProfilePictureLink(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value9(Boolean value) {
        setIsBanned(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value10(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public StoreOwnerRecord value11(LocalDateTime value) {
        setModificationTime(value);
        return this;
    }

    @Override
    public StoreOwnerRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, Boolean value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreOwnerRecord
     */
    public StoreOwnerRecord() {
        super(StoreOwner.STORE_OWNER);
    }

    /**
     * Create a detached, initialised StoreOwnerRecord
     */
    public StoreOwnerRecord(Long storeOwnerId, Long storeId, String cognitoUserId, String cognitoUserPoolId, String email, String phoneNumber, String username, String profilePictureLink, Boolean isBanned, LocalDateTime creationTime, LocalDateTime modificationTime) {
        super(StoreOwner.STORE_OWNER);

        setStoreOwnerId(storeOwnerId);
        setStoreId(storeId);
        setCognitoUserId(cognitoUserId);
        setCognitoUserPoolId(cognitoUserPoolId);
        setEmail(email);
        setPhoneNumber(phoneNumber);
        setUsername(username);
        setProfilePictureLink(profilePictureLink);
        setIsBanned(isBanned);
        setCreationTime(creationTime);
        setModificationTime(modificationTime);
    }

    /**
     * Create a detached, initialised StoreOwnerRecord
     */
    public StoreOwnerRecord(com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos.StoreOwner value) {
        super(StoreOwner.STORE_OWNER);

        if (value != null) {
            setStoreOwnerId(value.getStoreOwnerId());
            setStoreId(value.getStoreId());
            setCognitoUserId(value.getCognitoUserId());
            setCognitoUserPoolId(value.getCognitoUserPoolId());
            setEmail(value.getEmail());
            setPhoneNumber(value.getPhoneNumber());
            setUsername(value.getUsername());
            setProfilePictureLink(value.getProfilePictureLink());
            setIsBanned(value.getIsBanned());
            setCreationTime(value.getCreationTime());
            setModificationTime(value.getModificationTime());
        }
    }
}
