/*
 * This file is generated by jOOQ.
 */
package eCommerceServiceDataAccessLayer;


import eCommerceServiceDataAccessLayer.tables.Customer;
import eCommerceServiceDataAccessLayer.tables.Product;
import eCommerceServiceDataAccessLayer.tables.ProductBrand;
import eCommerceServiceDataAccessLayer.tables.ProductBrandMap;
import eCommerceServiceDataAccessLayer.tables.ProductCategory;
import eCommerceServiceDataAccessLayer.tables.ProductCategoryMap;
import eCommerceServiceDataAccessLayer.tables.ProductImage;
import eCommerceServiceDataAccessLayer.tables.ProductTag;
import eCommerceServiceDataAccessLayer.tables.ProductTagMap;
import eCommerceServiceDataAccessLayer.tables.Store;
import eCommerceServiceDataAccessLayer.tables.StoreCategory;
import eCommerceServiceDataAccessLayer.tables.StoreCategoryMap;
import eCommerceServiceDataAccessLayer.tables.StoreImage;
import eCommerceServiceDataAccessLayer.tables.StoreLocation;
import eCommerceServiceDataAccessLayer.tables.StoreOwner;
import eCommerceServiceDataAccessLayer.tables.records.CustomerRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductBrandMapRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductBrandRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductCategoryMapRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductCategoryRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductImageRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductTagMapRecord;
import eCommerceServiceDataAccessLayer.tables.records.ProductTagRecord;
import eCommerceServiceDataAccessLayer.tables.records.StoreCategoryMapRecord;
import eCommerceServiceDataAccessLayer.tables.records.StoreCategoryRecord;
import eCommerceServiceDataAccessLayer.tables.records.StoreImageRecord;
import eCommerceServiceDataAccessLayer.tables.records.StoreLocationRecord;
import eCommerceServiceDataAccessLayer.tables.records.StoreOwnerRecord;
import eCommerceServiceDataAccessLayer.tables.records.StoreRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * Catbirdnyc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_COGNITO_USER_ID = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("KEY_customer_cognito_user_id"), new TableField[] { Customer.CUSTOMER.COGNITO_USER_ID }, true);
    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_EMAIL = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("KEY_customer_email"), new TableField[] { Customer.CUSTOMER.EMAIL }, true);
    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("KEY_customer_PRIMARY"), new TableField[] { Customer.CUSTOMER.CUSTOMER_ID }, true);
    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_USERNAME = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("KEY_customer_username"), new TableField[] { Customer.CUSTOMER.USERNAME }, true);
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("KEY_product_PRIMARY"), new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_UNIQUE_PRODUCT_NAME_IN_STORE = Internal.createUniqueKey(Product.PRODUCT, DSL.name("KEY_product_unique_product_name_in_store"), new TableField[] { Product.PRODUCT.STORE_ID, Product.PRODUCT.UNIQUE_PRODUCT_NAME_IN_STORE }, true);
    public static final UniqueKey<ProductBrandRecord> KEY_PRODUCT_BRAND_PRIMARY = Internal.createUniqueKey(ProductBrand.PRODUCT_BRAND, DSL.name("KEY_product_brand_PRIMARY"), new TableField[] { ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID }, true);
    public static final UniqueKey<ProductBrandMapRecord> KEY_PRODUCT_BRAND_MAP_PRIMARY = Internal.createUniqueKey(ProductBrandMap.PRODUCT_BRAND_MAP, DSL.name("KEY_product_brand_map_PRIMARY"), new TableField[] { ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID }, true);
    public static final UniqueKey<ProductCategoryRecord> KEY_PRODUCT_CATEGORY_PRIMARY = Internal.createUniqueKey(ProductCategory.PRODUCT_CATEGORY, DSL.name("KEY_product_category_PRIMARY"), new TableField[] { ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID }, true);
    public static final UniqueKey<ProductCategoryRecord> KEY_PRODUCT_CATEGORY_UK_PRODUCT_CATEGORY_C_CATEGORY_TYPE = Internal.createUniqueKey(ProductCategory.PRODUCT_CATEGORY, DSL.name("KEY_product_category_UK_product_category_C_category_type"), new TableField[] { ProductCategory.PRODUCT_CATEGORY.CATEGORY_TYPE }, true);
    public static final UniqueKey<ProductCategoryMapRecord> KEY_PRODUCT_CATEGORY_MAP_PRIMARY = Internal.createUniqueKey(ProductCategoryMap.PRODUCT_CATEGORY_MAP, DSL.name("KEY_product_category_map_PRIMARY"), new TableField[] { ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID }, true);
    public static final UniqueKey<ProductImageRecord> KEY_PRODUCT_IMAGE_PRIMARY = Internal.createUniqueKey(ProductImage.PRODUCT_IMAGE, DSL.name("KEY_product_image_PRIMARY"), new TableField[] { ProductImage.PRODUCT_IMAGE.PRODUCT_IMAGE_ID }, true);
    public static final UniqueKey<ProductTagRecord> KEY_PRODUCT_TAG_PRIMARY = Internal.createUniqueKey(ProductTag.PRODUCT_TAG, DSL.name("KEY_product_tag_PRIMARY"), new TableField[] { ProductTag.PRODUCT_TAG.PRODUCT_TAG_ID }, true);
    public static final UniqueKey<ProductTagMapRecord> KEY_PRODUCT_TAG_MAP_PRIMARY = Internal.createUniqueKey(ProductTagMap.PRODUCT_TAG_MAP, DSL.name("KEY_product_tag_map_PRIMARY"), new TableField[] { ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID }, true);
    public static final UniqueKey<StoreRecord> KEY_STORE_PRIMARY = Internal.createUniqueKey(Store.STORE, DSL.name("KEY_store_PRIMARY"), new TableField[] { Store.STORE.STORE_ID }, true);
    public static final UniqueKey<StoreRecord> KEY_STORE_UNIQUE_STORE_NAME = Internal.createUniqueKey(Store.STORE, DSL.name("KEY_store_unique_store_name"), new TableField[] { Store.STORE.UNIQUE_STORE_NAME }, true);
    public static final UniqueKey<StoreCategoryRecord> KEY_STORE_CATEGORY_CATEGORY_TYPE = Internal.createUniqueKey(StoreCategory.STORE_CATEGORY, DSL.name("KEY_store_category_category_type"), new TableField[] { StoreCategory.STORE_CATEGORY.CATEGORY_TYPE }, true);
    public static final UniqueKey<StoreCategoryRecord> KEY_STORE_CATEGORY_PRIMARY = Internal.createUniqueKey(StoreCategory.STORE_CATEGORY, DSL.name("KEY_store_category_PRIMARY"), new TableField[] { StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID }, true);
    public static final UniqueKey<StoreCategoryMapRecord> KEY_STORE_CATEGORY_MAP_PRIMARY = Internal.createUniqueKey(StoreCategoryMap.STORE_CATEGORY_MAP, DSL.name("KEY_store_category_map_PRIMARY"), new TableField[] { StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID }, true);
    public static final UniqueKey<StoreImageRecord> KEY_STORE_IMAGE_PRIMARY = Internal.createUniqueKey(StoreImage.STORE_IMAGE, DSL.name("KEY_store_image_PRIMARY"), new TableField[] { StoreImage.STORE_IMAGE.STORE_IMAGE_ID }, true);
    public static final UniqueKey<StoreLocationRecord> KEY_STORE_LOCATION_PRIMARY = Internal.createUniqueKey(StoreLocation.STORE_LOCATION, DSL.name("KEY_store_location_PRIMARY"), new TableField[] { StoreLocation.STORE_LOCATION.STORE_LOCATION_ID }, true);
    public static final UniqueKey<StoreOwnerRecord> KEY_STORE_OWNER_COGNITO_USER_ID = Internal.createUniqueKey(StoreOwner.STORE_OWNER, DSL.name("KEY_store_owner_cognito_user_id"), new TableField[] { StoreOwner.STORE_OWNER.COGNITO_USER_ID }, true);
    public static final UniqueKey<StoreOwnerRecord> KEY_STORE_OWNER_EMAIL = Internal.createUniqueKey(StoreOwner.STORE_OWNER, DSL.name("KEY_store_owner_email"), new TableField[] { StoreOwner.STORE_OWNER.EMAIL }, true);
    public static final UniqueKey<StoreOwnerRecord> KEY_STORE_OWNER_PHONE_NUMBER = Internal.createUniqueKey(StoreOwner.STORE_OWNER, DSL.name("KEY_store_owner_phone_number"), new TableField[] { StoreOwner.STORE_OWNER.PHONE_NUMBER }, true);
    public static final UniqueKey<StoreOwnerRecord> KEY_STORE_OWNER_PRIMARY = Internal.createUniqueKey(StoreOwner.STORE_OWNER, DSL.name("KEY_store_owner_PRIMARY"), new TableField[] { StoreOwner.STORE_OWNER.STORE_OWNER_ID }, true);
    public static final UniqueKey<StoreOwnerRecord> KEY_STORE_OWNER_USERNAME = Internal.createUniqueKey(StoreOwner.STORE_OWNER, DSL.name("KEY_store_owner_username"), new TableField[] { StoreOwner.STORE_OWNER.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProductRecord, StoreRecord> FK_PRODUCT_RT_STORE_RC_STORE_ID = Internal.createForeignKey(Product.PRODUCT, DSL.name("FK_product_RT_store_RC_store_id"), new TableField[] { Product.PRODUCT.STORE_ID }, Keys.KEY_STORE_PRIMARY, new TableField[] { Store.STORE.STORE_ID }, true);
    public static final ForeignKey<ProductBrandMapRecord, ProductBrandRecord> FK_PRODUCT_BRAND_MAP_RT_PRODUCT_BRAND_RC_PRODUCT_BRAND_ID = Internal.createForeignKey(ProductBrandMap.PRODUCT_BRAND_MAP, DSL.name("FK_product_brand_map_RT_product_brand_RC_product_brand_id"), new TableField[] { ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID }, Keys.KEY_PRODUCT_BRAND_PRIMARY, new TableField[] { ProductBrand.PRODUCT_BRAND.PRODUCT_BRAND_ID }, true);
    public static final ForeignKey<ProductBrandMapRecord, ProductRecord> FK_PRODUCT_BRAND_MAP_RT_PRODUCT_RC_PRODUCT_ID = Internal.createForeignKey(ProductBrandMap.PRODUCT_BRAND_MAP, DSL.name("FK_product_brand_map_RT_product_RC_product_id"), new TableField[] { ProductBrandMap.PRODUCT_BRAND_MAP.PRODUCT_ID }, Keys.KEY_PRODUCT_PRIMARY, new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final ForeignKey<ProductCategoryMapRecord, ProductRecord> FK_PRODUCT_CATEGORY_MAP_RT_PRODUCT_PRODUCT_ID_RC_PRODUCT_ID = Internal.createForeignKey(ProductCategoryMap.PRODUCT_CATEGORY_MAP, DSL.name("FK_product_category_map_RT_product_product_id_RC_product_id"), new TableField[] { ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_ID }, Keys.KEY_PRODUCT_PRIMARY, new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final ForeignKey<ProductCategoryMapRecord, ProductCategoryRecord> FK_PRODUCT_CATEGORY_MAP_T_PRODUCT_CATEGORY_C_PRODUCT_CATEGORY_ID = Internal.createForeignKey(ProductCategoryMap.PRODUCT_CATEGORY_MAP, DSL.name("FK_product_category_map_T_product_category_C_product_category_id"), new TableField[] { ProductCategoryMap.PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID }, Keys.KEY_PRODUCT_CATEGORY_PRIMARY, new TableField[] { ProductCategory.PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID }, true);
    public static final ForeignKey<ProductImageRecord, ProductRecord> PRODUCT_IMAGE_IBFK_1 = Internal.createForeignKey(ProductImage.PRODUCT_IMAGE, DSL.name("product_image_ibfk_1"), new TableField[] { ProductImage.PRODUCT_IMAGE.PRODUCT_ID }, Keys.KEY_PRODUCT_PRIMARY, new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final ForeignKey<ProductTagMapRecord, ProductRecord> PRODUCT_TAG_MAP_IBFK_1 = Internal.createForeignKey(ProductTagMap.PRODUCT_TAG_MAP, DSL.name("product_tag_map_ibfk_1"), new TableField[] { ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_ID }, Keys.KEY_PRODUCT_PRIMARY, new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final ForeignKey<ProductTagMapRecord, ProductTagRecord> PRODUCT_TAG_MAP_IBFK_2 = Internal.createForeignKey(ProductTagMap.PRODUCT_TAG_MAP, DSL.name("product_tag_map_ibfk_2"), new TableField[] { ProductTagMap.PRODUCT_TAG_MAP.PRODUCT_TAG_ID }, Keys.KEY_PRODUCT_TAG_PRIMARY, new TableField[] { ProductTag.PRODUCT_TAG.PRODUCT_TAG_ID }, true);
    public static final ForeignKey<StoreCategoryMapRecord, StoreCategoryRecord> FK_STORE_CATEGORY_MAP_RT_STORE_CATEGORY_RC_STORE_CATEGORY_ID = Internal.createForeignKey(StoreCategoryMap.STORE_CATEGORY_MAP, DSL.name("FK_store_category_map_RT_store_category_RC_store_category_id"), new TableField[] { StoreCategoryMap.STORE_CATEGORY_MAP.STORE_CATEGORY_ID }, Keys.KEY_STORE_CATEGORY_PRIMARY, new TableField[] { StoreCategory.STORE_CATEGORY.STORE_CATEGORY_ID }, true);
    public static final ForeignKey<StoreCategoryMapRecord, StoreRecord> FK_STORE_CATEGORY_MAP_RT_STORE_RC_STORE_ID = Internal.createForeignKey(StoreCategoryMap.STORE_CATEGORY_MAP, DSL.name("FK_store_category_map_RT_store_RC_store_id"), new TableField[] { StoreCategoryMap.STORE_CATEGORY_MAP.STORE_ID }, Keys.KEY_STORE_PRIMARY, new TableField[] { Store.STORE.STORE_ID }, true);
    public static final ForeignKey<StoreImageRecord, StoreRecord> FK_STORE_IMAGE_RT_STORE_RC_STORE_ID = Internal.createForeignKey(StoreImage.STORE_IMAGE, DSL.name("FK_store_image_RT_store_RC_store_id"), new TableField[] { StoreImage.STORE_IMAGE.STORE_ID }, Keys.KEY_STORE_PRIMARY, new TableField[] { Store.STORE.STORE_ID }, true);
    public static final ForeignKey<StoreLocationRecord, StoreRecord> FK_STORE_LOCATION_RT_STORE_RC_STORE_ID = Internal.createForeignKey(StoreLocation.STORE_LOCATION, DSL.name("FK_store_location_RT_store_RC_store_id"), new TableField[] { StoreLocation.STORE_LOCATION.STORE_ID }, Keys.KEY_STORE_PRIMARY, new TableField[] { Store.STORE.STORE_ID }, true);
    public static final ForeignKey<StoreOwnerRecord, StoreRecord> FK_STORE_OWNER_RT_STORE_RC_STORE_ID = Internal.createForeignKey(StoreOwner.STORE_OWNER, DSL.name("FK_store_owner_RT_store_RC_store_id"), new TableField[] { StoreOwner.STORE_OWNER.STORE_ID }, Keys.KEY_STORE_PRIMARY, new TableField[] { Store.STORE.STORE_ID }, true);
}
