/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          productImageId;
    private Long          productId;
    private String        productImageLink;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductImage() {}

    public ProductImage(ProductImage value) {
        this.productImageId = value.productImageId;
        this.productId = value.productId;
        this.productImageLink = value.productImageLink;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductImage(
        Long          productImageId,
        Long          productId,
        String        productImageLink,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productImageId = productImageId;
        this.productId = productId;
        this.productImageLink = productImageLink;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>PRODUCT_IMAGE.PRODUCT_IMAGE_ID</code>.
     */
    public Long getProductImageId() {
        return this.productImageId;
    }

    /**
     * Setter for <code>PRODUCT_IMAGE.PRODUCT_IMAGE_ID</code>.
     */
    public void setProductImageId(Long productImageId) {
        this.productImageId = productImageId;
    }

    /**
     * Getter for <code>PRODUCT_IMAGE.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>PRODUCT_IMAGE.PRODUCT_ID</code>.
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>PRODUCT_IMAGE.PRODUCT_IMAGE_LINK</code>.
     */
    public String getProductImageLink() {
        return this.productImageLink;
    }

    /**
     * Setter for <code>PRODUCT_IMAGE.PRODUCT_IMAGE_LINK</code>.
     */
    public void setProductImageLink(String productImageLink) {
        this.productImageLink = productImageLink;
    }

    /**
     * Getter for <code>PRODUCT_IMAGE.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>PRODUCT_IMAGE.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>PRODUCT_IMAGE.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>PRODUCT_IMAGE.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductImage (");

        sb.append(productImageId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productImageLink);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
