/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBrandMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          productBrandMapId;
    private Long          productId;
    private Long          productBrandId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductBrandMap() {}

    public ProductBrandMap(ProductBrandMap value) {
        this.productBrandMapId = value.productBrandMapId;
        this.productId = value.productId;
        this.productBrandId = value.productBrandId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductBrandMap(
        Long          productBrandMapId,
        Long          productId,
        Long          productBrandId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productBrandMapId = productBrandMapId;
        this.productId = productId;
        this.productBrandId = productBrandId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID</code>.
     */
    public Long getProductBrandMapId() {
        return this.productBrandMapId;
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_MAP_ID</code>.
     */
    public void setProductBrandMapId(Long productBrandMapId) {
        this.productBrandMapId = productBrandMapId;
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.PRODUCT_ID</code>.
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID</code>.
     */
    public Long getProductBrandId() {
        return this.productBrandId;
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.PRODUCT_BRAND_ID</code>.
     */
    public void setProductBrandId(Long productBrandId) {
        this.productBrandId = productBrandId;
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>PRODUCT_BRAND_MAP.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>PRODUCT_BRAND_MAP.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductBrandMap (");

        sb.append(productBrandMapId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productBrandId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
