/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          productCategoryMapId;
    private Long          productId;
    private Long          productCategoryId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductCategoryMap() {}

    public ProductCategoryMap(ProductCategoryMap value) {
        this.productCategoryMapId = value.productCategoryMapId;
        this.productId = value.productId;
        this.productCategoryId = value.productCategoryId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductCategoryMap(
        Long          productCategoryMapId,
        Long          productId,
        Long          productCategoryId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productCategoryMapId = productCategoryMapId;
        this.productId = productId;
        this.productCategoryId = productCategoryId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID</code>.
     */
    public Long getProductCategoryMapId() {
        return this.productCategoryMapId;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_MAP_ID</code>.
     */
    public void setProductCategoryMapId(Long productCategoryMapId) {
        this.productCategoryMapId = productCategoryMapId;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY_MAP.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY_MAP.PRODUCT_ID</code>.
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID</code>.
     */
    public Long getProductCategoryId() {
        return this.productCategoryId;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY_MAP.PRODUCT_CATEGORY_ID</code>.
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY_MAP.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY_MAP.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY_MAP.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY_MAP.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductCategoryMap (");

        sb.append(productCategoryMapId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productCategoryId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
