/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          productCategoryId;
    private String        categoryType;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductCategory() {}

    public ProductCategory(ProductCategory value) {
        this.productCategoryId = value.productCategoryId;
        this.categoryType = value.categoryType;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductCategory(
        Long          productCategoryId,
        String        categoryType,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productCategoryId = productCategoryId;
        this.categoryType = categoryType;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID</code>.
     */
    public Long getProductCategoryId() {
        return this.productCategoryId;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.PRODUCT_CATEGORY_ID</code>.
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.CATEGORY_TYPE</code>.
     */
    public String getCategoryType() {
        return this.categoryType;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.CATEGORY_TYPE</code>.
     */
    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>PRODUCT_CATEGORY.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>PRODUCT_CATEGORY.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductCategory (");

        sb.append(productCategoryId);
        sb.append(", ").append(categoryType);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
