/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTagMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          productTagMapId;
    private Long          productId;
    private Long          productTagId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public ProductTagMap() {}

    public ProductTagMap(ProductTagMap value) {
        this.productTagMapId = value.productTagMapId;
        this.productId = value.productId;
        this.productTagId = value.productTagId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public ProductTagMap(
        Long          productTagMapId,
        Long          productId,
        Long          productTagId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.productTagMapId = productTagMapId;
        this.productId = productId;
        this.productTagId = productTagId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID</code>.
     */
    public Long getProductTagMapId() {
        return this.productTagMapId;
    }

    /**
     * Setter for <code>PRODUCT_TAG_MAP.PRODUCT_TAG_MAP_ID</code>.
     */
    public void setProductTagMapId(Long productTagMapId) {
        this.productTagMapId = productTagMapId;
    }

    /**
     * Getter for <code>PRODUCT_TAG_MAP.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>PRODUCT_TAG_MAP.PRODUCT_ID</code>.
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>PRODUCT_TAG_MAP.PRODUCT_TAG_ID</code>.
     */
    public Long getProductTagId() {
        return this.productTagId;
    }

    /**
     * Setter for <code>PRODUCT_TAG_MAP.PRODUCT_TAG_ID</code>.
     */
    public void setProductTagId(Long productTagId) {
        this.productTagId = productTagId;
    }

    /**
     * Getter for <code>PRODUCT_TAG_MAP.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>PRODUCT_TAG_MAP.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>PRODUCT_TAG_MAP.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>PRODUCT_TAG_MAP.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductTagMap (");

        sb.append(productTagMapId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productTagId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
