/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreOwner implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          storeOwnerId;
    private Long          storeId;
    private String        cognitoUserId;
    private String        cognitoUserPoolId;
    private String        email;
    private String        phoneNumber;
    private String        username;
    private String        profilePictureLink;
    private Boolean       isBanned;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreOwner() {}

    public StoreOwner(StoreOwner value) {
        this.storeOwnerId = value.storeOwnerId;
        this.storeId = value.storeId;
        this.cognitoUserId = value.cognitoUserId;
        this.cognitoUserPoolId = value.cognitoUserPoolId;
        this.email = value.email;
        this.phoneNumber = value.phoneNumber;
        this.username = value.username;
        this.profilePictureLink = value.profilePictureLink;
        this.isBanned = value.isBanned;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreOwner(
        Long          storeOwnerId,
        Long          storeId,
        String        cognitoUserId,
        String        cognitoUserPoolId,
        String        email,
        String        phoneNumber,
        String        username,
        String        profilePictureLink,
        Boolean       isBanned,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeOwnerId = storeOwnerId;
        this.storeId = storeId;
        this.cognitoUserId = cognitoUserId;
        this.cognitoUserPoolId = cognitoUserPoolId;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.username = username;
        this.profilePictureLink = profilePictureLink;
        this.isBanned = isBanned;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>STORE_OWNER.STORE_OWNER_ID</code>.
     */
    public Long getStoreOwnerId() {
        return this.storeOwnerId;
    }

    /**
     * Setter for <code>STORE_OWNER.STORE_OWNER_ID</code>.
     */
    public void setStoreOwnerId(Long storeOwnerId) {
        this.storeOwnerId = storeOwnerId;
    }

    /**
     * Getter for <code>STORE_OWNER.STORE_ID</code>.
     */
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>STORE_OWNER.STORE_ID</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>STORE_OWNER.COGNITO_USER_ID</code>.
     */
    public String getCognitoUserId() {
        return this.cognitoUserId;
    }

    /**
     * Setter for <code>STORE_OWNER.COGNITO_USER_ID</code>.
     */
    public void setCognitoUserId(String cognitoUserId) {
        this.cognitoUserId = cognitoUserId;
    }

    /**
     * Getter for <code>STORE_OWNER.COGNITO_USER_POOL_ID</code>.
     */
    public String getCognitoUserPoolId() {
        return this.cognitoUserPoolId;
    }

    /**
     * Setter for <code>STORE_OWNER.COGNITO_USER_POOL_ID</code>.
     */
    public void setCognitoUserPoolId(String cognitoUserPoolId) {
        this.cognitoUserPoolId = cognitoUserPoolId;
    }

    /**
     * Getter for <code>STORE_OWNER.EMAIL</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>STORE_OWNER.EMAIL</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>STORE_OWNER.PHONE_NUMBER</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>STORE_OWNER.PHONE_NUMBER</code>.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>STORE_OWNER.USERNAME</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>STORE_OWNER.USERNAME</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>STORE_OWNER.PROFILE_PICTURE_LINK</code>.
     */
    public String getProfilePictureLink() {
        return this.profilePictureLink;
    }

    /**
     * Setter for <code>STORE_OWNER.PROFILE_PICTURE_LINK</code>.
     */
    public void setProfilePictureLink(String profilePictureLink) {
        this.profilePictureLink = profilePictureLink;
    }

    /**
     * Getter for <code>STORE_OWNER.IS_BANNED</code>.
     */
    public Boolean getIsBanned() {
        return this.isBanned;
    }

    /**
     * Setter for <code>STORE_OWNER.IS_BANNED</code>.
     */
    public void setIsBanned(Boolean isBanned) {
        this.isBanned = isBanned;
    }

    /**
     * Getter for <code>STORE_OWNER.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>STORE_OWNER.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>STORE_OWNER.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>STORE_OWNER.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreOwner (");

        sb.append(storeOwnerId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(cognitoUserId);
        sb.append(", ").append(cognitoUserPoolId);
        sb.append(", ").append(email);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(username);
        sb.append(", ").append(profilePictureLink);
        sb.append(", ").append(isBanned);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
