/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreLocation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          storeLocationId;
    private Long          storeId;
    private String        formattedAddress;
    private BigDecimal    latitude;
    private BigDecimal    longitude;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreLocation() {}

    public StoreLocation(StoreLocation value) {
        this.storeLocationId = value.storeLocationId;
        this.storeId = value.storeId;
        this.formattedAddress = value.formattedAddress;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreLocation(
        Long          storeLocationId,
        Long          storeId,
        String        formattedAddress,
        BigDecimal    latitude,
        BigDecimal    longitude,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeLocationId = storeLocationId;
        this.storeId = storeId;
        this.formattedAddress = formattedAddress;
        this.latitude = latitude;
        this.longitude = longitude;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>STORE_LOCATION.STORE_LOCATION_ID</code>.
     */
    public Long getStoreLocationId() {
        return this.storeLocationId;
    }

    /**
     * Setter for <code>STORE_LOCATION.STORE_LOCATION_ID</code>.
     */
    public void setStoreLocationId(Long storeLocationId) {
        this.storeLocationId = storeLocationId;
    }

    /**
     * Getter for <code>STORE_LOCATION.STORE_ID</code>.
     */
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>STORE_LOCATION.STORE_ID</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>STORE_LOCATION.FORMATTED_ADDRESS</code>.
     */
    public String getFormattedAddress() {
        return this.formattedAddress;
    }

    /**
     * Setter for <code>STORE_LOCATION.FORMATTED_ADDRESS</code>.
     */
    public void setFormattedAddress(String formattedAddress) {
        this.formattedAddress = formattedAddress;
    }

    /**
     * Getter for <code>STORE_LOCATION.LATITUDE</code>.
     */
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>STORE_LOCATION.LATITUDE</code>.
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>STORE_LOCATION.LONGITUDE</code>.
     */
    public BigDecimal getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>STORE_LOCATION.LONGITUDE</code>.
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for <code>STORE_LOCATION.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>STORE_LOCATION.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>STORE_LOCATION.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>STORE_LOCATION.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreLocation (");

        sb.append(storeLocationId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(formattedAddress);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
