/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      storeImageId;
    private UInteger      storeId;
    private String        storeImageLink;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreImage() {}

    public StoreImage(StoreImage value) {
        this.storeImageId = value.storeImageId;
        this.storeId = value.storeId;
        this.storeImageLink = value.storeImageLink;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreImage(
        UInteger      storeImageId,
        UInteger      storeId,
        String        storeImageLink,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeImageId = storeImageId;
        this.storeId = storeId;
        this.storeImageLink = storeImageLink;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.store_image_id</code>.
     */
    public UInteger getStoreImageId() {
        return this.storeImageId;
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.store_image_id</code>.
     */
    public void setStoreImageId(UInteger storeImageId) {
        this.storeImageId = storeImageId;
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.store_id</code>.
     */
    public UInteger getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.store_id</code>.
     */
    public void setStoreId(UInteger storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.store_image_link</code>.
     */
    public String getStoreImageLink() {
        return this.storeImageLink;
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.store_image_link</code>.
     */
    public void setStoreImageLink(String storeImageLink) {
        this.storeImageLink = storeImageLink;
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.creation_time</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.creation_time</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>Catbirdnyc.store_image.modification_time</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>Catbirdnyc.store_image.modification_time</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreImage (");

        sb.append(storeImageId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(storeImageLink);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
