/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          storeImageId;
    private Long          storeId;
    private String        storeImageLink;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreImage() {}

    public StoreImage(StoreImage value) {
        this.storeImageId = value.storeImageId;
        this.storeId = value.storeId;
        this.storeImageLink = value.storeImageLink;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreImage(
        Long          storeImageId,
        Long          storeId,
        String        storeImageLink,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeImageId = storeImageId;
        this.storeId = storeId;
        this.storeImageLink = storeImageLink;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>STORE_IMAGE.STORE_IMAGE_ID</code>.
     */
    public Long getStoreImageId() {
        return this.storeImageId;
    }

    /**
     * Setter for <code>STORE_IMAGE.STORE_IMAGE_ID</code>.
     */
    public void setStoreImageId(Long storeImageId) {
        this.storeImageId = storeImageId;
    }

    /**
     * Getter for <code>STORE_IMAGE.STORE_ID</code>.
     */
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>STORE_IMAGE.STORE_ID</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>STORE_IMAGE.STORE_IMAGE_LINK</code>.
     */
    public String getStoreImageLink() {
        return this.storeImageLink;
    }

    /**
     * Setter for <code>STORE_IMAGE.STORE_IMAGE_LINK</code>.
     */
    public void setStoreImageLink(String storeImageLink) {
        this.storeImageLink = storeImageLink;
    }

    /**
     * Getter for <code>STORE_IMAGE.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>STORE_IMAGE.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>STORE_IMAGE.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>STORE_IMAGE.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreImage (");

        sb.append(storeImageId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(storeImageLink);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
