/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          storeCategoryId;
    private String        categoryType;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreCategory() {}

    public StoreCategory(StoreCategory value) {
        this.storeCategoryId = value.storeCategoryId;
        this.categoryType = value.categoryType;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreCategory(
        Long          storeCategoryId,
        String        categoryType,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeCategoryId = storeCategoryId;
        this.categoryType = categoryType;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>STORE_CATEGORY.STORE_CATEGORY_ID</code>.
     */
    public Long getStoreCategoryId() {
        return this.storeCategoryId;
    }

    /**
     * Setter for <code>STORE_CATEGORY.STORE_CATEGORY_ID</code>.
     */
    public void setStoreCategoryId(Long storeCategoryId) {
        this.storeCategoryId = storeCategoryId;
    }

    /**
     * Getter for <code>STORE_CATEGORY.CATEGORY_TYPE</code>.
     */
    public String getCategoryType() {
        return this.categoryType;
    }

    /**
     * Setter for <code>STORE_CATEGORY.CATEGORY_TYPE</code>.
     */
    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * Getter for <code>STORE_CATEGORY.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>STORE_CATEGORY.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>STORE_CATEGORY.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>STORE_CATEGORY.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreCategory (");

        sb.append(storeCategoryId);
        sb.append(", ").append(categoryType);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
