/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          storeId;
    private String        uniqueStoreName;
    private String        contactNumber;
    private String        contactEmail;
    private String        storeName;
    private String        storeWebsite;
    private String        storeDescription;
    private String        storeCoverImage;
    private String        yelpLink;
    private String        facebookLink;
    private String        instagramLink;
    private String        twitterLink;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public Store() {}

    public Store(Store value) {
        this.storeId = value.storeId;
        this.uniqueStoreName = value.uniqueStoreName;
        this.contactNumber = value.contactNumber;
        this.contactEmail = value.contactEmail;
        this.storeName = value.storeName;
        this.storeWebsite = value.storeWebsite;
        this.storeDescription = value.storeDescription;
        this.storeCoverImage = value.storeCoverImage;
        this.yelpLink = value.yelpLink;
        this.facebookLink = value.facebookLink;
        this.instagramLink = value.instagramLink;
        this.twitterLink = value.twitterLink;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public Store(
        Long          storeId,
        String        uniqueStoreName,
        String        contactNumber,
        String        contactEmail,
        String        storeName,
        String        storeWebsite,
        String        storeDescription,
        String        storeCoverImage,
        String        yelpLink,
        String        facebookLink,
        String        instagramLink,
        String        twitterLink,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeId = storeId;
        this.uniqueStoreName = uniqueStoreName;
        this.contactNumber = contactNumber;
        this.contactEmail = contactEmail;
        this.storeName = storeName;
        this.storeWebsite = storeWebsite;
        this.storeDescription = storeDescription;
        this.storeCoverImage = storeCoverImage;
        this.yelpLink = yelpLink;
        this.facebookLink = facebookLink;
        this.instagramLink = instagramLink;
        this.twitterLink = twitterLink;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>STORE.STORE_ID</code>.
     */
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>STORE.STORE_ID</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>STORE.UNIQUE_STORE_NAME</code>.
     */
    public String getUniqueStoreName() {
        return this.uniqueStoreName;
    }

    /**
     * Setter for <code>STORE.UNIQUE_STORE_NAME</code>.
     */
    public void setUniqueStoreName(String uniqueStoreName) {
        this.uniqueStoreName = uniqueStoreName;
    }

    /**
     * Getter for <code>STORE.CONTACT_NUMBER</code>.
     */
    public String getContactNumber() {
        return this.contactNumber;
    }

    /**
     * Setter for <code>STORE.CONTACT_NUMBER</code>.
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    /**
     * Getter for <code>STORE.CONTACT_EMAIL</code>.
     */
    public String getContactEmail() {
        return this.contactEmail;
    }

    /**
     * Setter for <code>STORE.CONTACT_EMAIL</code>.
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * Getter for <code>STORE.STORE_NAME</code>.
     */
    public String getStoreName() {
        return this.storeName;
    }

    /**
     * Setter for <code>STORE.STORE_NAME</code>.
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * Getter for <code>STORE.STORE_WEBSITE</code>.
     */
    public String getStoreWebsite() {
        return this.storeWebsite;
    }

    /**
     * Setter for <code>STORE.STORE_WEBSITE</code>.
     */
    public void setStoreWebsite(String storeWebsite) {
        this.storeWebsite = storeWebsite;
    }

    /**
     * Getter for <code>STORE.STORE_DESCRIPTION</code>.
     */
    public String getStoreDescription() {
        return this.storeDescription;
    }

    /**
     * Setter for <code>STORE.STORE_DESCRIPTION</code>.
     */
    public void setStoreDescription(String storeDescription) {
        this.storeDescription = storeDescription;
    }

    /**
     * Getter for <code>STORE.STORE_COVER_IMAGE</code>.
     */
    public String getStoreCoverImage() {
        return this.storeCoverImage;
    }

    /**
     * Setter for <code>STORE.STORE_COVER_IMAGE</code>.
     */
    public void setStoreCoverImage(String storeCoverImage) {
        this.storeCoverImage = storeCoverImage;
    }

    /**
     * Getter for <code>STORE.YELP_LINK</code>.
     */
    public String getYelpLink() {
        return this.yelpLink;
    }

    /**
     * Setter for <code>STORE.YELP_LINK</code>.
     */
    public void setYelpLink(String yelpLink) {
        this.yelpLink = yelpLink;
    }

    /**
     * Getter for <code>STORE.FACEBOOK_LINK</code>.
     */
    public String getFacebookLink() {
        return this.facebookLink;
    }

    /**
     * Setter for <code>STORE.FACEBOOK_LINK</code>.
     */
    public void setFacebookLink(String facebookLink) {
        this.facebookLink = facebookLink;
    }

    /**
     * Getter for <code>STORE.INSTAGRAM_LINK</code>.
     */
    public String getInstagramLink() {
        return this.instagramLink;
    }

    /**
     * Setter for <code>STORE.INSTAGRAM_LINK</code>.
     */
    public void setInstagramLink(String instagramLink) {
        this.instagramLink = instagramLink;
    }

    /**
     * Getter for <code>STORE.TWITTER_LINK</code>.
     */
    public String getTwitterLink() {
        return this.twitterLink;
    }

    /**
     * Setter for <code>STORE.TWITTER_LINK</code>.
     */
    public void setTwitterLink(String twitterLink) {
        this.twitterLink = twitterLink;
    }

    /**
     * Getter for <code>STORE.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>STORE.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>STORE.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>STORE.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(storeId);
        sb.append(", ").append(uniqueStoreName);
        sb.append(", ").append(contactNumber);
        sb.append(", ").append(contactEmail);
        sb.append(", ").append(storeName);
        sb.append(", ").append(storeWebsite);
        sb.append(", ").append(storeDescription);
        sb.append(", ").append(storeCoverImage);
        sb.append(", ").append(yelpLink);
        sb.append(", ").append(facebookLink);
        sb.append(", ").append(instagramLink);
        sb.append(", ").append(twitterLink);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
