/*
 * This file is generated by jOOQ.
 */
package com.bimelody.ecommerceservice.dataaccesslayer.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreCategoryMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          storeCategoryMapId;
    private Long          storeId;
    private Long          storeCategoryId;
    private LocalDateTime creationTime;
    private LocalDateTime modificationTime;

    public StoreCategoryMap() {}

    public StoreCategoryMap(StoreCategoryMap value) {
        this.storeCategoryMapId = value.storeCategoryMapId;
        this.storeId = value.storeId;
        this.storeCategoryId = value.storeCategoryId;
        this.creationTime = value.creationTime;
        this.modificationTime = value.modificationTime;
    }

    public StoreCategoryMap(
        Long          storeCategoryMapId,
        Long          storeId,
        Long          storeCategoryId,
        LocalDateTime creationTime,
        LocalDateTime modificationTime
    ) {
        this.storeCategoryMapId = storeCategoryMapId;
        this.storeId = storeId;
        this.storeCategoryId = storeCategoryId;
        this.creationTime = creationTime;
        this.modificationTime = modificationTime;
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID</code>.
     */
    public Long getStoreCategoryMapId() {
        return this.storeCategoryMapId;
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_MAP_ID</code>.
     */
    public void setStoreCategoryMapId(Long storeCategoryMapId) {
        this.storeCategoryMapId = storeCategoryMapId;
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.STORE_ID</code>.
     */
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.STORE_ID</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_ID</code>.
     */
    public Long getStoreCategoryId() {
        return this.storeCategoryId;
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.STORE_CATEGORY_ID</code>.
     */
    public void setStoreCategoryId(Long storeCategoryId) {
        this.storeCategoryId = storeCategoryId;
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.CREATION_TIME</code>.
     */
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.CREATION_TIME</code>.
     */
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>STORE_CATEGORY_MAP.MODIFICATION_TIME</code>.
     */
    public LocalDateTime getModificationTime() {
        return this.modificationTime;
    }

    /**
     * Setter for <code>STORE_CATEGORY_MAP.MODIFICATION_TIME</code>.
     */
    public void setModificationTime(LocalDateTime modificationTime) {
        this.modificationTime = modificationTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreCategoryMap (");

        sb.append(storeCategoryMapId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(storeCategoryId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(modificationTime);

        sb.append(")");
        return sb.toString();
    }
}
